#ifndef GUARD_CONSTANTS_EVENT_OBJECTS_H
#define GUARD_CONSTANTS_EVENT_OBJECTS_H

#define OBJ_EVENT_GFX_BRENDAN_NORMAL               0
#define OBJ_EVENT_GFX_BRENDAN_MACH_BIKE            1
#define OBJ_EVENT_GFX_BRENDAN_SURFING              2
#define OBJ_EVENT_GFX_BRENDAN_FIELD_MOVE           3
#define OBJ_EVENT_GFX_QUINTY_PLUMP                 4
#define OBJ_EVENT_GFX_NINJA_BOY                    5
#define OBJ_EVENT_GFX_TWIN                         6
#define OBJ_EVENT_GFX_BOY_1                        7
#define OBJ_EVENT_GFX_GIRL_1                       8
#define OBJ_EVENT_GFX_BOY_2                        9
#define OBJ_EVENT_GFX_GIRL_2                      10
#define OBJ_EVENT_GFX_LITTLE_BOY                  11
#define OBJ_EVENT_GFX_LITTLE_GIRL                 12
#define OBJ_EVENT_GFX_BOY_3                       13
#define OBJ_EVENT_GFX_GIRL_3                      14
#define OBJ_EVENT_GFX_RICH_BOY                    15
#define OBJ_EVENT_GFX_WOMAN_1                     16
#define OBJ_EVENT_GFX_FAT_MAN                     17
#define OBJ_EVENT_GFX_POKEFAN_F                   18
#define OBJ_EVENT_GFX_MAN_1                       19
#define OBJ_EVENT_GFX_WOMAN_2                     20
#define OBJ_EVENT_GFX_EXPERT_M                    21
#define OBJ_EVENT_GFX_EXPERT_F                    22
#define OBJ_EVENT_GFX_MAN_2                       23
#define OBJ_EVENT_GFX_WOMAN_3                     24
#define OBJ_EVENT_GFX_POKEFAN_M                   25
#define OBJ_EVENT_GFX_WOMAN_4                     26
#define OBJ_EVENT_GFX_COOK                        27
#define OBJ_EVENT_GFX_LINK_RECEPTIONIST           28
#define OBJ_EVENT_GFX_OLD_MAN                     29
#define OBJ_EVENT_GFX_OLD_WOMAN                   30
#define OBJ_EVENT_GFX_CAMPER                      31
#define OBJ_EVENT_GFX_PICNICKER                   32
#define OBJ_EVENT_GFX_MAN_3                       33
#define OBJ_EVENT_GFX_WOMAN_5                     34
#define OBJ_EVENT_GFX_YOUNGSTER                   35
#define OBJ_EVENT_GFX_BUG_CATCHER                 36
#define OBJ_EVENT_GFX_PSYCHIC_M                   37
#define OBJ_EVENT_GFX_SCHOOL_KID_M                38
#define OBJ_EVENT_GFX_MANIAC                      39
#define OBJ_EVENT_GFX_HEX_MANIAC                  40
#define OBJ_EVENT_GFX_RAYQUAZA_STILL              41
#define OBJ_EVENT_GFX_SWIMMER_M                   42
#define OBJ_EVENT_GFX_SWIMMER_F                   43
#define OBJ_EVENT_GFX_BLACK_BELT                  44
#define OBJ_EVENT_GFX_BEAUTY                      45
#define OBJ_EVENT_GFX_SCIENTIST_1                 46
#define OBJ_EVENT_GFX_LASS                        47
#define OBJ_EVENT_GFX_GENTLEMAN                   48
#define OBJ_EVENT_GFX_SAILOR                      49
#define OBJ_EVENT_GFX_FISHERMAN                   50
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_M        51
#define OBJ_EVENT_GFX_RUNNING_TRIATHLETE_F        52
#define OBJ_EVENT_GFX_TUBER_F                     53
#define OBJ_EVENT_GFX_TUBER_M                     54
#define OBJ_EVENT_GFX_HIKER                       55
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_M        56
#define OBJ_EVENT_GFX_CYCLING_TRIATHLETE_F        57
#define OBJ_EVENT_GFX_NURSE                       58
#define OBJ_EVENT_GFX_ITEM_BALL                   59
#define OBJ_EVENT_GFX_BERRY_TREE                  60
#define OBJ_EVENT_GFX_BERRY_TREE_EARLY_STAGES     61
#define OBJ_EVENT_GFX_BERRY_TREE_LATE_STAGES      62
#define OBJ_EVENT_GFX_BRENDAN_ACRO_BIKE           63
#define OBJ_EVENT_GFX_PROF_BIRCH                  64
#define OBJ_EVENT_GFX_MAN_4                       65
#define OBJ_EVENT_GFX_MAN_5                       66
#define OBJ_EVENT_GFX_REPORTER_M                  67
#define OBJ_EVENT_GFX_REPORTER_F                  68
#define OBJ_EVENT_GFX_BARD                        69
#define OBJ_EVENT_GFX_ANABEL                      70
#define OBJ_EVENT_GFX_TUCKER                      71
#define OBJ_EVENT_GFX_GRETA                       72
#define OBJ_EVENT_GFX_SPENSER                     73
#define OBJ_EVENT_GFX_NOLAND                      74
#define OBJ_EVENT_GFX_LUCY                        75
#define OBJ_EVENT_GFX_UNUSED_NATU_DOLL            76
#define OBJ_EVENT_GFX_UNUSED_MAGNEMITE_DOLL       77
#define OBJ_EVENT_GFX_UNUSED_SQUIRTLE_DOLL        78
#define OBJ_EVENT_GFX_UNUSED_WOOPER_DOLL          79
#define OBJ_EVENT_GFX_UNUSED_PIKACHU_DOLL         80
#define OBJ_EVENT_GFX_UNUSED_PORYGON2_DOLL        81
#define OBJ_EVENT_GFX_CUTTABLE_TREE               82
#define OBJ_EVENT_GFX_MART_EMPLOYEE               83
#define OBJ_EVENT_GFX_ROOFTOP_SALE_WOMAN          84
#define OBJ_EVENT_GFX_TEALA                       85
#define OBJ_EVENT_GFX_BREAKABLE_ROCK              86
#define OBJ_EVENT_GFX_PUSHABLE_BOULDER            87
#define OBJ_EVENT_GFX_MR_BRINEYS_BOAT             88
#define OBJ_EVENT_GFX_MAY_NORMAL                  89
#define OBJ_EVENT_GFX_MAY_MACH_BIKE               90
#define OBJ_EVENT_GFX_MAY_ACRO_BIKE               91
#define OBJ_EVENT_GFX_MAY_SURFING                 92
#define OBJ_EVENT_GFX_MAY_FIELD_MOVE              93
#define OBJ_EVENT_GFX_TRUCK                       94
#define OBJ_EVENT_GFX_VIGOROTH_CARRYING_BOX       95
#define OBJ_EVENT_GFX_VIGOROTH_FACING_AWAY        96
#define OBJ_EVENT_GFX_BIRCHS_BAG                  97
#define OBJ_EVENT_GFX_ZIGZAGOON_1                 98
#define OBJ_EVENT_GFX_ARTIST                      99
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_NORMAL       100
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_MACH_BIKE    101
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_ACRO_BIKE    102
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_SURFING      103
#define OBJ_EVENT_GFX_RIVAL_BRENDAN_FIELD_MOVE   104
#define OBJ_EVENT_GFX_RIVAL_MAY_NORMAL           105
#define OBJ_EVENT_GFX_RIVAL_MAY_MACH_BIKE        106
#define OBJ_EVENT_GFX_RIVAL_MAY_ACRO_BIKE        107
#define OBJ_EVENT_GFX_RIVAL_MAY_SURFING          108
#define OBJ_EVENT_GFX_RIVAL_MAY_FIELD_MOVE       109
#define OBJ_EVENT_GFX_CAMERAMAN                  110
#define OBJ_EVENT_GFX_BRENDAN_UNDERWATER         111
#define OBJ_EVENT_GFX_MAY_UNDERWATER             112
#define OBJ_EVENT_GFX_MOVING_BOX                 113
#define OBJ_EVENT_GFX_CABLE_CAR                  114
#define OBJ_EVENT_GFX_SCIENTIST_2                115
#define OBJ_EVENT_GFX_DEVON_EMPLOYEE             116
#define OBJ_EVENT_GFX_AQUA_MEMBER_M              117
#define OBJ_EVENT_GFX_AQUA_MEMBER_F              118
#define OBJ_EVENT_GFX_MAGMA_MEMBER_M             119
#define OBJ_EVENT_GFX_MAGMA_MEMBER_F             120
#define OBJ_EVENT_GFX_SIDNEY                     121
#define OBJ_EVENT_GFX_PHOEBE                     122
#define OBJ_EVENT_GFX_GLACIA                     123
#define OBJ_EVENT_GFX_DRAKE                      124
#define OBJ_EVENT_GFX_ROXANNE                    125
#define OBJ_EVENT_GFX_BRAWLY                     126
#define OBJ_EVENT_GFX_WATTSON                    127
#define OBJ_EVENT_GFX_FLANNERY                   128
#define OBJ_EVENT_GFX_NORMAN                     129
#define OBJ_EVENT_GFX_WINONA                     130
#define OBJ_EVENT_GFX_LIZA                       131
#define OBJ_EVENT_GFX_TATE                       132
#define OBJ_EVENT_GFX_WALLACE                    133
#define OBJ_EVENT_GFX_STEVEN                     134
#define OBJ_EVENT_GFX_WALLY                      135
#define OBJ_EVENT_GFX_LITTLE_BOY_3               136
#define OBJ_EVENT_GFX_BRENDAN_FISHING            137
#define OBJ_EVENT_GFX_MAY_FISHING                138
#define OBJ_EVENT_GFX_HOT_SPRINGS_OLD_WOMAN      139
#define OBJ_EVENT_GFX_SS_TIDAL                   140
#define OBJ_EVENT_GFX_SUBMARINE_SHADOW           141
#define OBJ_EVENT_GFX_PICHU_DOLL                 142
#define OBJ_EVENT_GFX_PIKACHU_DOLL               143
#define OBJ_EVENT_GFX_MARILL_DOLL                144
#define OBJ_EVENT_GFX_TOGEPI_DOLL                145
#define OBJ_EVENT_GFX_CYNDAQUIL_DOLL             146
#define OBJ_EVENT_GFX_CHIKORITA_DOLL             147
#define OBJ_EVENT_GFX_TOTODILE_DOLL              148
#define OBJ_EVENT_GFX_JIGGLYPUFF_DOLL            149
#define OBJ_EVENT_GFX_MEOWTH_DOLL                150
#define OBJ_EVENT_GFX_CLEFAIRY_DOLL              151
#define OBJ_EVENT_GFX_DITTO_DOLL                 152
#define OBJ_EVENT_GFX_SMOOCHUM_DOLL              153
#define OBJ_EVENT_GFX_TREECKO_DOLL               154
#define OBJ_EVENT_GFX_TORCHIC_DOLL               155
#define OBJ_EVENT_GFX_MUDKIP_DOLL                156
#define OBJ_EVENT_GFX_DUSKULL_DOLL               157
#define OBJ_EVENT_GFX_WYNAUT_DOLL                158
#define OBJ_EVENT_GFX_BALTOY_DOLL                159
#define OBJ_EVENT_GFX_KECLEON_DOLL               160
#define OBJ_EVENT_GFX_AZURILL_DOLL               161
#define OBJ_EVENT_GFX_SKITTY_DOLL                162
#define OBJ_EVENT_GFX_SWABLU_DOLL                163
#define OBJ_EVENT_GFX_GULPIN_DOLL                164
#define OBJ_EVENT_GFX_LOTAD_DOLL                 165
#define OBJ_EVENT_GFX_SEEDOT_DOLL                166
#define OBJ_EVENT_GFX_PIKA_CUSHION               167
#define OBJ_EVENT_GFX_ROUND_CUSHION              168
#define OBJ_EVENT_GFX_KISS_CUSHION               169
#define OBJ_EVENT_GFX_ZIGZAG_CUSHION             170
#define OBJ_EVENT_GFX_SPIN_CUSHION               171
#define OBJ_EVENT_GFX_DIAMOND_CUSHION            172
#define OBJ_EVENT_GFX_BALL_CUSHION               173
#define OBJ_EVENT_GFX_GRASS_CUSHION              174
#define OBJ_EVENT_GFX_FIRE_CUSHION               175
#define OBJ_EVENT_GFX_WATER_CUSHION              176
#define OBJ_EVENT_GFX_BIG_SNORLAX_DOLL           177
#define OBJ_EVENT_GFX_BIG_RHYDON_DOLL            178
#define OBJ_EVENT_GFX_BIG_LAPRAS_DOLL            179
#define OBJ_EVENT_GFX_BIG_VENUSAUR_DOLL          180
#define OBJ_EVENT_GFX_BIG_CHARIZARD_DOLL         181
#define OBJ_EVENT_GFX_BIG_BLASTOISE_DOLL         182
#define OBJ_EVENT_GFX_BIG_WAILMER_DOLL           183
#define OBJ_EVENT_GFX_BIG_REGIROCK_DOLL          184
#define OBJ_EVENT_GFX_BIG_REGICE_DOLL            185
#define OBJ_EVENT_GFX_BIG_REGISTEEL_DOLL         186
#define OBJ_EVENT_GFX_LATIAS                     187
#define OBJ_EVENT_GFX_LATIOS                     188
#define OBJ_EVENT_GFX_GAMEBOY_KID                189
#define OBJ_EVENT_GFX_CONTEST_JUDGE              190
#define OBJ_EVENT_GFX_BRENDAN_WATERING           191
#define OBJ_EVENT_GFX_MAY_WATERING               192
#define OBJ_EVENT_GFX_BRENDAN_DECORATING         193
#define OBJ_EVENT_GFX_MAY_DECORATING             194
#define OBJ_EVENT_GFX_ARCHIE                     195
#define OBJ_EVENT_GFX_MAXIE                      196
#define OBJ_EVENT_GFX_KYOGRE_FRONT               197
#define OBJ_EVENT_GFX_GROUDON_FRONT              198
#define OBJ_EVENT_GFX_FOSSIL                     199
#define OBJ_EVENT_GFX_REGIROCK                   200
#define OBJ_EVENT_GFX_REGICE                     201
#define OBJ_EVENT_GFX_REGISTEEL                  202
#define OBJ_EVENT_GFX_SKITTY                     203
#define OBJ_EVENT_GFX_KECLEON                    204
#define OBJ_EVENT_GFX_KYOGRE_ASLEEP              205
#define OBJ_EVENT_GFX_GROUDON_ASLEEP             206
#define OBJ_EVENT_GFX_RAYQUAZA                   207
#define OBJ_EVENT_GFX_ZIGZAGOON_2                208
#define OBJ_EVENT_GFX_PIKACHU                    209
#define OBJ_EVENT_GFX_AZUMARILL                  210
#define OBJ_EVENT_GFX_WINGULL                    211
#define OBJ_EVENT_GFX_KECLEON_BRIDGE_SHADOW      212
#define OBJ_EVENT_GFX_TUBER_M_SWIMMING           213
#define OBJ_EVENT_GFX_AZURILL                    214
#define OBJ_EVENT_GFX_MOM                        215
#define OBJ_EVENT_GFX_LINK_BRENDAN               216
#define OBJ_EVENT_GFX_LINK_MAY                   217
#define OBJ_EVENT_GFX_JUAN                       218
#define OBJ_EVENT_GFX_SCOTT                      219
#define OBJ_EVENT_GFX_POOCHYENA                  220
#define OBJ_EVENT_GFX_KYOGRE_SIDE                221
#define OBJ_EVENT_GFX_GROUDON_SIDE               222
#define OBJ_EVENT_GFX_MYSTERY_GIFT_MAN           223
#define OBJ_EVENT_GFX_TRICK_HOUSE_STATUE         224
#define OBJ_EVENT_GFX_KIRLIA                     225
#define OBJ_EVENT_GFX_DUSCLOPS                   226
#define OBJ_EVENT_GFX_UNION_ROOM_NURSE           227
#define OBJ_EVENT_GFX_SUDOWOODO                  228
#define OBJ_EVENT_GFX_MEW                        229
#define OBJ_EVENT_GFX_RED                        230
#define OBJ_EVENT_GFX_LEAF                       231
#define OBJ_EVENT_GFX_DEOXYS                     232
#define OBJ_EVENT_GFX_DEOXYS_TRIANGLE            233
#define OBJ_EVENT_GFX_BRANDON                    234
#define OBJ_EVENT_GFX_LINK_RS_BRENDAN            235
#define OBJ_EVENT_GFX_LINK_RS_MAY                236
#define OBJ_EVENT_GFX_LUGIA                      237
#define OBJ_EVENT_GFX_HOOH                       238
#define OBJ_EVENT_GFX_PSYCHIC_F                  239
#define OBJ_EVENT_GFX_AQUA_ADMIN_M               240
#define OBJ_EVENT_GFX_AQUA_ADMIN_F               241
#define OBJ_EVENT_GFX_MAGMA_ADMIN_F              242

#define NUM_REGULAR_OBJ_EVENT_GFX                (OBJ_EVENT_GFX_MAGMA_ADMIN_F + 1)

//Pokemon overworlds

//Gen 1 (151
#define OBJ_EVENT_GFX_POKEMON_BULBASAUR		     (NUM_REGULAR_OBJ_EVENT_GFX + 0)//001
#define OBJ_EVENT_GFX_POKEMON_IVYSAUR		     (NUM_REGULAR_OBJ_EVENT_GFX + 1)//002
#define OBJ_EVENT_GFX_POKEMON_VENUSAUR		     (NUM_REGULAR_OBJ_EVENT_GFX + 2)//003
#define OBJ_EVENT_GFX_POKEMON_CHARMANDER		 (NUM_REGULAR_OBJ_EVENT_GFX + 3)//004
#define OBJ_EVENT_GFX_POKEMON_CHARMELEON		 (NUM_REGULAR_OBJ_EVENT_GFX + 4)//005
#define OBJ_EVENT_GFX_POKEMON_CHARIZARD		     (NUM_REGULAR_OBJ_EVENT_GFX + 5)//006
#define OBJ_EVENT_GFX_POKEMON_SQUIRTLE		     (NUM_REGULAR_OBJ_EVENT_GFX + 6)//007
#define OBJ_EVENT_GFX_POKEMON_WARTORTLE		     (NUM_REGULAR_OBJ_EVENT_GFX + 7)//008
#define OBJ_EVENT_GFX_POKEMON_BLASTOISE		     (NUM_REGULAR_OBJ_EVENT_GFX + 8)//009
#define OBJ_EVENT_GFX_POKEMON_CATERPIE		     (NUM_REGULAR_OBJ_EVENT_GFX + 9)//010
#define OBJ_EVENT_GFX_POKEMON_METAPOD		     (NUM_REGULAR_OBJ_EVENT_GFX + 10)//011
#define OBJ_EVENT_GFX_POKEMON_BUTTERFREE		 (NUM_REGULAR_OBJ_EVENT_GFX + 11)//012
#define OBJ_EVENT_GFX_POKEMON_WEEDLE		     (NUM_REGULAR_OBJ_EVENT_GFX + 12)//013
#define OBJ_EVENT_GFX_POKEMON_KAKUNA		     (NUM_REGULAR_OBJ_EVENT_GFX + 13)//014
#define OBJ_EVENT_GFX_POKEMON_BEEDRILL		     (NUM_REGULAR_OBJ_EVENT_GFX + 14)//015
#define OBJ_EVENT_GFX_POKEMON_PIDGEY		     (NUM_REGULAR_OBJ_EVENT_GFX + 15)//016
#define OBJ_EVENT_GFX_POKEMON_PIDGEOTTO		     (NUM_REGULAR_OBJ_EVENT_GFX + 16)//017
#define OBJ_EVENT_GFX_POKEMON_PIDGEOT		     (NUM_REGULAR_OBJ_EVENT_GFX + 17)//018
#define OBJ_EVENT_GFX_POKEMON_RATTATA		     (NUM_REGULAR_OBJ_EVENT_GFX + 18)//019
#define OBJ_EVENT_GFX_POKEMON_RATICATE		     (NUM_REGULAR_OBJ_EVENT_GFX + 19)//020
#define OBJ_EVENT_GFX_POKEMON_SPEAROW		     (NUM_REGULAR_OBJ_EVENT_GFX + 20)//021
#define OBJ_EVENT_GFX_POKEMON_FEAROW		     (NUM_REGULAR_OBJ_EVENT_GFX + 21)//022
#define OBJ_EVENT_GFX_POKEMON_EKANS		         (NUM_REGULAR_OBJ_EVENT_GFX + 22)//023
#define OBJ_EVENT_GFX_POKEMON_ARBOK		         (NUM_REGULAR_OBJ_EVENT_GFX + 23)//024
#define OBJ_EVENT_GFX_POKEMON_PIKACHU		     (NUM_REGULAR_OBJ_EVENT_GFX + 24)//025
#define OBJ_EVENT_GFX_POKEMON_RAICHU		     (NUM_REGULAR_OBJ_EVENT_GFX + 25)//026
#define OBJ_EVENT_GFX_POKEMON_SANDSHREW		     (NUM_REGULAR_OBJ_EVENT_GFX + 26)//027
#define OBJ_EVENT_GFX_POKEMON_SANDSLASH		     (NUM_REGULAR_OBJ_EVENT_GFX + 27)//028
#define OBJ_EVENT_GFX_POKEMON_NIDORAN_F		     (NUM_REGULAR_OBJ_EVENT_GFX + 28)//029
#define OBJ_EVENT_GFX_POKEMON_NIDORINA		     (NUM_REGULAR_OBJ_EVENT_GFX + 29)//030
#define OBJ_EVENT_GFX_POKEMON_NIDOQUEEN		     (NUM_REGULAR_OBJ_EVENT_GFX + 30)//031
#define OBJ_EVENT_GFX_POKEMON_NIDORAN_M		     (NUM_REGULAR_OBJ_EVENT_GFX + 31)//032
#define OBJ_EVENT_GFX_POKEMON_NIDORINO		     (NUM_REGULAR_OBJ_EVENT_GFX + 32)//033
#define OBJ_EVENT_GFX_POKEMON_NIDOKING		     (NUM_REGULAR_OBJ_EVENT_GFX + 33)//034
#define OBJ_EVENT_GFX_POKEMON_CLEFAIRY		     (NUM_REGULAR_OBJ_EVENT_GFX + 34)//035
#define OBJ_EVENT_GFX_POKEMON_CLEFABLE		     (NUM_REGULAR_OBJ_EVENT_GFX + 35)//036
#define OBJ_EVENT_GFX_POKEMON_VULPIX		     (NUM_REGULAR_OBJ_EVENT_GFX + 36)//037
#define OBJ_EVENT_GFX_POKEMON_NINETAILS		     (NUM_REGULAR_OBJ_EVENT_GFX + 37)//038
#define OBJ_EVENT_GFX_POKEMON_JIGGLYPUFF		 (NUM_REGULAR_OBJ_EVENT_GFX + 38)//039
#define OBJ_EVENT_GFX_POKEMON_WIGGLYTUFF		 (NUM_REGULAR_OBJ_EVENT_GFX + 39)//040
#define OBJ_EVENT_GFX_POKEMON_ZUBAT		         (NUM_REGULAR_OBJ_EVENT_GFX + 40)//041
#define OBJ_EVENT_GFX_POKEMON_GOLBAT		     (NUM_REGULAR_OBJ_EVENT_GFX + 41)//042
#define OBJ_EVENT_GFX_POKEMON_ODDISH		     (NUM_REGULAR_OBJ_EVENT_GFX + 42)//043
#define OBJ_EVENT_GFX_POKEMON_GLOOM		         (NUM_REGULAR_OBJ_EVENT_GFX + 43)//044
#define OBJ_EVENT_GFX_POKEMON_VILEPLUME		     (NUM_REGULAR_OBJ_EVENT_GFX + 44)//045
#define OBJ_EVENT_GFX_POKEMON_PARAS		         (NUM_REGULAR_OBJ_EVENT_GFX + 45)//046
#define OBJ_EVENT_GFX_POKEMON_PARASECT		     (NUM_REGULAR_OBJ_EVENT_GFX + 46)//047
#define OBJ_EVENT_GFX_POKEMON_VENONAT		     (NUM_REGULAR_OBJ_EVENT_GFX + 47)//048
#define OBJ_EVENT_GFX_POKEMON_VENOMOTH		     (NUM_REGULAR_OBJ_EVENT_GFX + 48)//049
#define OBJ_EVENT_GFX_POKEMON_DIGLETT		     (NUM_REGULAR_OBJ_EVENT_GFX + 49)//050
#define OBJ_EVENT_GFX_POKEMON_DUGTRIO		     (NUM_REGULAR_OBJ_EVENT_GFX + 50)//051
#define OBJ_EVENT_GFX_POKEMON_MEOWTH		     (NUM_REGULAR_OBJ_EVENT_GFX + 51)//052
#define OBJ_EVENT_GFX_POKEMON_PERSIAN		     (NUM_REGULAR_OBJ_EVENT_GFX + 52)//053
#define OBJ_EVENT_GFX_POKEMON_PSYDUCK		     (NUM_REGULAR_OBJ_EVENT_GFX + 53)//054
#define OBJ_EVENT_GFX_POKEMON_GOLDUCK		     (NUM_REGULAR_OBJ_EVENT_GFX + 54)//055
#define OBJ_EVENT_GFX_POKEMON_MANKEY		     (NUM_REGULAR_OBJ_EVENT_GFX + 55)//056
#define OBJ_EVENT_GFX_POKEMON_PRIMAPE		     (NUM_REGULAR_OBJ_EVENT_GFX + 56)//057
#define OBJ_EVENT_GFX_POKEMON_GROWLITHE		     (NUM_REGULAR_OBJ_EVENT_GFX + 57)//058
#define OBJ_EVENT_GFX_POKEMON_ARCANINE		     (NUM_REGULAR_OBJ_EVENT_GFX + 58)//059
#define OBJ_EVENT_GFX_POKEMON_POLIWAG		     (NUM_REGULAR_OBJ_EVENT_GFX + 59)//060
#define OBJ_EVENT_GFX_POKEMON_POLIWHIRL		     (NUM_REGULAR_OBJ_EVENT_GFX + 60)//061
#define OBJ_EVENT_GFX_POKEMON_POLIWRATH		     (NUM_REGULAR_OBJ_EVENT_GFX + 61)//062
#define OBJ_EVENT_GFX_POKEMON_ABRA		         (NUM_REGULAR_OBJ_EVENT_GFX + 62)//063
#define OBJ_EVENT_GFX_POKEMON_KADABRA		     (NUM_REGULAR_OBJ_EVENT_GFX + 63)//064
#define OBJ_EVENT_GFX_POKEMON_ALAKAZAM		     (NUM_REGULAR_OBJ_EVENT_GFX + 64)//065
#define OBJ_EVENT_GFX_POKEMON_MACHOP		     (NUM_REGULAR_OBJ_EVENT_GFX + 65)//066
#define OBJ_EVENT_GFX_POKEMON_MACHOKE		     (NUM_REGULAR_OBJ_EVENT_GFX + 66)//067
#define OBJ_EVENT_GFX_POKEMON_MACHAMP		     (NUM_REGULAR_OBJ_EVENT_GFX + 67)//068
#define OBJ_EVENT_GFX_POKEMON_BELLSPROUT		 (NUM_REGULAR_OBJ_EVENT_GFX + 68)//069
#define OBJ_EVENT_GFX_POKEMON_WEEPINBELL		 (NUM_REGULAR_OBJ_EVENT_GFX + 69)//070
#define OBJ_EVENT_GFX_POKEMON_VICTREEBELL		 (NUM_REGULAR_OBJ_EVENT_GFX + 70)//071
#define OBJ_EVENT_GFX_POKEMON_TENTACOOL		     (NUM_REGULAR_OBJ_EVENT_GFX + 71)//072
#define OBJ_EVENT_GFX_POKEMON_TENTACRUEL		 (NUM_REGULAR_OBJ_EVENT_GFX + 72)//073
#define OBJ_EVENT_GFX_POKEMON_GEODUDE		     (NUM_REGULAR_OBJ_EVENT_GFX + 73)//074
#define OBJ_EVENT_GFX_POKEMON_GRAVELER		     (NUM_REGULAR_OBJ_EVENT_GFX + 74)//075
#define OBJ_EVENT_GFX_POKEMON_GOLEM		         (NUM_REGULAR_OBJ_EVENT_GFX + 75)//076
#define OBJ_EVENT_GFX_POKEMON_PONYTA		     (NUM_REGULAR_OBJ_EVENT_GFX + 76)//077
#define OBJ_EVENT_GFX_POKEMON_RAPIDASH		     (NUM_REGULAR_OBJ_EVENT_GFX + 77)//078
#define OBJ_EVENT_GFX_POKEMON_SLOWPOKE		     (NUM_REGULAR_OBJ_EVENT_GFX + 78)//079
#define OBJ_EVENT_GFX_POKEMON_SLOWBRO		     (NUM_REGULAR_OBJ_EVENT_GFX + 79)//080
#define OBJ_EVENT_GFX_POKEMON_MAGNEMITE		     (NUM_REGULAR_OBJ_EVENT_GFX + 80)//081
#define OBJ_EVENT_GFX_POKEMON_MAGNETON		     (NUM_REGULAR_OBJ_EVENT_GFX + 81)//082
#define OBJ_EVENT_GFX_POKEMON_FARFETCHD		     (NUM_REGULAR_OBJ_EVENT_GFX + 82)//083
#define OBJ_EVENT_GFX_POKEMON_DODUO		         (NUM_REGULAR_OBJ_EVENT_GFX + 83)//084
#define OBJ_EVENT_GFX_POKEMON_DODRIO		     (NUM_REGULAR_OBJ_EVENT_GFX + 84)//085
#define OBJ_EVENT_GFX_POKEMON_SEEL		         (NUM_REGULAR_OBJ_EVENT_GFX + 85)//086
#define OBJ_EVENT_GFX_POKEMON_DEWGONG		     (NUM_REGULAR_OBJ_EVENT_GFX + 86)//087
#define OBJ_EVENT_GFX_POKEMON_GRIMER		     (NUM_REGULAR_OBJ_EVENT_GFX + 87)//088
#define OBJ_EVENT_GFX_POKEMON_MUK		         (NUM_REGULAR_OBJ_EVENT_GFX + 88)//089
#define OBJ_EVENT_GFX_POKEMON_SHELLDER		     (NUM_REGULAR_OBJ_EVENT_GFX + 89)//090
#define OBJ_EVENT_GFX_POKEMON_CLOYSTER		     (NUM_REGULAR_OBJ_EVENT_GFX + 90)//091
#define OBJ_EVENT_GFX_POKEMON_GASTLY		     (NUM_REGULAR_OBJ_EVENT_GFX + 91)//092
#define OBJ_EVENT_GFX_POKEMON_HAUNTER		     (NUM_REGULAR_OBJ_EVENT_GFX + 92)//093
#define OBJ_EVENT_GFX_POKEMON_GENGAR		     (NUM_REGULAR_OBJ_EVENT_GFX + 93)//094
#define OBJ_EVENT_GFX_POKEMON_ONIX		         (NUM_REGULAR_OBJ_EVENT_GFX + 94)//095
#define OBJ_EVENT_GFX_POKEMON_DROWZEE		     (NUM_REGULAR_OBJ_EVENT_GFX + 95)//096
#define OBJ_EVENT_GFX_POKEMON_HYPNO		         (NUM_REGULAR_OBJ_EVENT_GFX + 96)//097
#define OBJ_EVENT_GFX_POKEMON_KRABBY		     (NUM_REGULAR_OBJ_EVENT_GFX + 97)//098
#define OBJ_EVENT_GFX_POKEMON_KINGLER		     (NUM_REGULAR_OBJ_EVENT_GFX + 98)//099
#define OBJ_EVENT_GFX_POKEMON_VOLTORB		     (NUM_REGULAR_OBJ_EVENT_GFX + 99)//100
#define OBJ_EVENT_GFX_POKEMON_ELECTRODE		     (NUM_REGULAR_OBJ_EVENT_GFX + 100)//101
#define OBJ_EVENT_GFX_POKEMON_EXEGGCUTE		     (NUM_REGULAR_OBJ_EVENT_GFX + 101)//102
#define OBJ_EVENT_GFX_POKEMON_EXEGGUTOR		     (NUM_REGULAR_OBJ_EVENT_GFX + 102)//103
#define OBJ_EVENT_GFX_POKEMON_CUBONE		     (NUM_REGULAR_OBJ_EVENT_GFX + 103)//104
#define OBJ_EVENT_GFX_POKEMON_MAROWAK		     (NUM_REGULAR_OBJ_EVENT_GFX + 104)//105
#define OBJ_EVENT_GFX_POKEMON_HITMONLEE		     (NUM_REGULAR_OBJ_EVENT_GFX + 105)//106
#define OBJ_EVENT_GFX_POKEMON_HITMONCHAN		 (NUM_REGULAR_OBJ_EVENT_GFX + 106)//107
#define OBJ_EVENT_GFX_POKEMON_LICKITUNG		     (NUM_REGULAR_OBJ_EVENT_GFX + 107)//108
#define OBJ_EVENT_GFX_POKEMON_KOFFING		     (NUM_REGULAR_OBJ_EVENT_GFX + 108)//109
#define OBJ_EVENT_GFX_POKEMON_WEEZING		     (NUM_REGULAR_OBJ_EVENT_GFX + 109)//110
#define OBJ_EVENT_GFX_POKEMON_RHYHORN		     (NUM_REGULAR_OBJ_EVENT_GFX + 110)//111
#define OBJ_EVENT_GFX_POKEMON_RHYDON		     (NUM_REGULAR_OBJ_EVENT_GFX + 111)//112
#define OBJ_EVENT_GFX_POKEMON_CHANSEY		     (NUM_REGULAR_OBJ_EVENT_GFX + 112)//113
#define OBJ_EVENT_GFX_POKEMON_WHATISTHAT		 (NUM_REGULAR_OBJ_EVENT_GFX + 113)//114
#define OBJ_EVENT_GFX_POKEMON_KANGASKHAN		 (NUM_REGULAR_OBJ_EVENT_GFX + 114)//115
#define OBJ_EVENT_GFX_POKEMON_HORSEA		     (NUM_REGULAR_OBJ_EVENT_GFX + 115)//116
#define OBJ_EVENT_GFX_POKEMON_SEADRA		     (NUM_REGULAR_OBJ_EVENT_GFX + 116)//117
#define OBJ_EVENT_GFX_POKEMON_GOLDEEN		     (NUM_REGULAR_OBJ_EVENT_GFX + 117)//118
#define OBJ_EVENT_GFX_POKEMON_SEAKING		     (NUM_REGULAR_OBJ_EVENT_GFX + 118)//119
#define OBJ_EVENT_GFX_POKEMON_STARYU		     (NUM_REGULAR_OBJ_EVENT_GFX + 119)//120
#define OBJ_EVENT_GFX_POKEMON_STARMIE		     (NUM_REGULAR_OBJ_EVENT_GFX + 120)//121
#define OBJ_EVENT_GFX_POKEMON_MR_MIME		     (NUM_REGULAR_OBJ_EVENT_GFX + 121)//122
#define OBJ_EVENT_GFX_POKEMON_SCYTHER		     (NUM_REGULAR_OBJ_EVENT_GFX + 122)//123
#define OBJ_EVENT_GFX_POKEMON_JYNX		         (NUM_REGULAR_OBJ_EVENT_GFX + 123)//124
#define OBJ_EVENT_GFX_POKEMON_ELECTABUZZ		 (NUM_REGULAR_OBJ_EVENT_GFX + 124)//125
#define OBJ_EVENT_GFX_POKEMON_MAGMAR		     (NUM_REGULAR_OBJ_EVENT_GFX + 125)//126
#define OBJ_EVENT_GFX_POKEMON_PINSIR		     (NUM_REGULAR_OBJ_EVENT_GFX + 126)//127
#define OBJ_EVENT_GFX_POKEMON_TAUROS		     (NUM_REGULAR_OBJ_EVENT_GFX + 127)//128
#define OBJ_EVENT_GFX_POKEMON_MAGIKARP		     (NUM_REGULAR_OBJ_EVENT_GFX + 128)//129
#define OBJ_EVENT_GFX_POKEMON_GYARADOS		     (NUM_REGULAR_OBJ_EVENT_GFX + 129)//130
#define OBJ_EVENT_GFX_POKEMON_LAPRAS		     (NUM_REGULAR_OBJ_EVENT_GFX + 130)//131
#define OBJ_EVENT_GFX_POKEMON_DITTO		         (NUM_REGULAR_OBJ_EVENT_GFX + 131)//132
#define OBJ_EVENT_GFX_POKEMON_EEVEE		         (NUM_REGULAR_OBJ_EVENT_GFX + 132)//133
#define OBJ_EVENT_GFX_POKEMON_VAPOREON		     (NUM_REGULAR_OBJ_EVENT_GFX + 133)//134
#define OBJ_EVENT_GFX_POKEMON_JOLTEON		     (NUM_REGULAR_OBJ_EVENT_GFX + 134)//135
#define OBJ_EVENT_GFX_POKEMON_FLAREON		     (NUM_REGULAR_OBJ_EVENT_GFX + 135)//136
#define OBJ_EVENT_GFX_POKEMON_PORYGON		     (NUM_REGULAR_OBJ_EVENT_GFX + 136)//137
#define OBJ_EVENT_GFX_POKEMON_OMANYTE		     (NUM_REGULAR_OBJ_EVENT_GFX + 137)//138
#define OBJ_EVENT_GFX_POKEMON_OMASTAR		     (NUM_REGULAR_OBJ_EVENT_GFX + 138)//139
#define OBJ_EVENT_GFX_POKEMON_KABUTO		     (NUM_REGULAR_OBJ_EVENT_GFX + 139)//140
#define OBJ_EVENT_GFX_POKEMON_KABUTOPS		     (NUM_REGULAR_OBJ_EVENT_GFX + 140)//141
#define OBJ_EVENT_GFX_POKEMON_AERODACTYL		 (NUM_REGULAR_OBJ_EVENT_GFX + 141)//142
#define OBJ_EVENT_GFX_POKEMON_SNORLAX		     (NUM_REGULAR_OBJ_EVENT_GFX + 142)//143
#define OBJ_EVENT_GFX_POKEMON_ARTICUNO		     (NUM_REGULAR_OBJ_EVENT_GFX + 143)//144
#define OBJ_EVENT_GFX_POKEMON_ZAPDOS		     (NUM_REGULAR_OBJ_EVENT_GFX + 144)//145
#define OBJ_EVENT_GFX_POKEMON_MOLTRES		     (NUM_REGULAR_OBJ_EVENT_GFX + 145)//146
#define OBJ_EVENT_GFX_POKEMON_DRATINI		     (NUM_REGULAR_OBJ_EVENT_GFX + 146)//147
#define OBJ_EVENT_GFX_POKEMON_DRAGONAIR		     (NUM_REGULAR_OBJ_EVENT_GFX + 147)//148
#define OBJ_EVENT_GFX_POKEMON_DRAGONITE		     (NUM_REGULAR_OBJ_EVENT_GFX + 148)//149
#define OBJ_EVENT_GFX_POKEMON_MEWTWO		     (NUM_REGULAR_OBJ_EVENT_GFX + 149)//150
#define OBJ_EVENT_GFX_POKEMON_MEW		         (NUM_REGULAR_OBJ_EVENT_GFX + 150)//151

//Gen 2 (100
#define OBJ_EVENT_GFX_POKEMON_CHIKORITA		     (NUM_REGULAR_OBJ_EVENT_GFX + 151)//152
#define OBJ_EVENT_GFX_POKEMON_BAYLEEF		     (NUM_REGULAR_OBJ_EVENT_GFX + 152)//153
#define OBJ_EVENT_GFX_POKEMON_MEGANIUM		     (NUM_REGULAR_OBJ_EVENT_GFX + 153)//154
#define OBJ_EVENT_GFX_POKEMON_CYNDAQUIL		     (NUM_REGULAR_OBJ_EVENT_GFX + 154)//155
#define OBJ_EVENT_GFX_POKEMON_QUILAVA		     (NUM_REGULAR_OBJ_EVENT_GFX + 155)//156
#define OBJ_EVENT_GFX_POKEMON_TYPHLOSION		 (NUM_REGULAR_OBJ_EVENT_GFX + 156)//157
#define OBJ_EVENT_GFX_POKEMON_TOTODILE		     (NUM_REGULAR_OBJ_EVENT_GFX + 157)//158
#define OBJ_EVENT_GFX_POKEMON_CROCONAW		     (NUM_REGULAR_OBJ_EVENT_GFX + 158)//159
#define OBJ_EVENT_GFX_POKEMON_FERALIGATR		 (NUM_REGULAR_OBJ_EVENT_GFX + 159)//160
#define OBJ_EVENT_GFX_POKEMON_SENTRET		     (NUM_REGULAR_OBJ_EVENT_GFX + 160)//161
#define OBJ_EVENT_GFX_POKEMON_FURRET		     (NUM_REGULAR_OBJ_EVENT_GFX + 161)//162
#define OBJ_EVENT_GFX_POKEMON_HOOTHOOT		     (NUM_REGULAR_OBJ_EVENT_GFX + 162)//163
#define OBJ_EVENT_GFX_POKEMON_NOCTOWL		     (NUM_REGULAR_OBJ_EVENT_GFX + 163)//164
#define OBJ_EVENT_GFX_POKEMON_LEDYBA		     (NUM_REGULAR_OBJ_EVENT_GFX + 164)//165
#define OBJ_EVENT_GFX_POKEMON_LEDIAN		     (NUM_REGULAR_OBJ_EVENT_GFX + 165)//166
#define OBJ_EVENT_GFX_POKEMON_SPINARAK		     (NUM_REGULAR_OBJ_EVENT_GFX + 166)//167
#define OBJ_EVENT_GFX_POKEMON_ARIADOS		     (NUM_REGULAR_OBJ_EVENT_GFX + 167)//168
#define OBJ_EVENT_GFX_POKEMON_CROBAT		     (NUM_REGULAR_OBJ_EVENT_GFX + 168)//169
#define OBJ_EVENT_GFX_POKEMON_CHINCHOU		     (NUM_REGULAR_OBJ_EVENT_GFX + 169)//170
#define OBJ_EVENT_GFX_POKEMON_LANTURN		     (NUM_REGULAR_OBJ_EVENT_GFX + 170)//171
#define OBJ_EVENT_GFX_POKEMON_PICHU		         (NUM_REGULAR_OBJ_EVENT_GFX + 171)//172
#define OBJ_EVENT_GFX_POKEMON_CLEFFA		     (NUM_REGULAR_OBJ_EVENT_GFX + 172)//173
#define OBJ_EVENT_GFX_POKEMON_IGGLYBUFF		     (NUM_REGULAR_OBJ_EVENT_GFX + 173)//174
#define OBJ_EVENT_GFX_POKEMON_TOGEPI		     (NUM_REGULAR_OBJ_EVENT_GFX + 174)//175
#define OBJ_EVENT_GFX_POKEMON_TOGETIC		     (NUM_REGULAR_OBJ_EVENT_GFX + 175)//176
#define OBJ_EVENT_GFX_POKEMON_NATU		         (NUM_REGULAR_OBJ_EVENT_GFX + 176)//177
#define OBJ_EVENT_GFX_POKEMON_XATU		         (NUM_REGULAR_OBJ_EVENT_GFX + 177)//178
#define OBJ_EVENT_GFX_POKEMON_MAREEP		     (NUM_REGULAR_OBJ_EVENT_GFX + 178)//179
#define OBJ_EVENT_GFX_POKEMON_FLAAFFY		     (NUM_REGULAR_OBJ_EVENT_GFX + 179)//180
#define OBJ_EVENT_GFX_POKEMON_AMPHAROS		     (NUM_REGULAR_OBJ_EVENT_GFX + 180)//181
#define OBJ_EVENT_GFX_POKEMON_BELLOSSOM		     (NUM_REGULAR_OBJ_EVENT_GFX + 181)//182
#define OBJ_EVENT_GFX_POKEMON_MARILL		     (NUM_REGULAR_OBJ_EVENT_GFX + 182)//183
#define OBJ_EVENT_GFX_POKEMON_AZUMARILL		     (NUM_REGULAR_OBJ_EVENT_GFX + 183)//184
#define OBJ_EVENT_GFX_POKEMON_SUDOWOODO		     (NUM_REGULAR_OBJ_EVENT_GFX + 184)//185
#define OBJ_EVENT_GFX_POKEMON_POLITOED		     (NUM_REGULAR_OBJ_EVENT_GFX + 185)//186
#define OBJ_EVENT_GFX_POKEMON_HOPPIP		     (NUM_REGULAR_OBJ_EVENT_GFX + 186)//187
#define OBJ_EVENT_GFX_POKEMON_SKIPLOOM		     (NUM_REGULAR_OBJ_EVENT_GFX + 187)//188
#define OBJ_EVENT_GFX_POKEMON_JUMPLUFF		     (NUM_REGULAR_OBJ_EVENT_GFX + 188)//189
#define OBJ_EVENT_GFX_POKEMON_AIPOM		         (NUM_REGULAR_OBJ_EVENT_GFX + 189)//190
#define OBJ_EVENT_GFX_POKEMON_SUNKERN		     (NUM_REGULAR_OBJ_EVENT_GFX + 190)//191
#define OBJ_EVENT_GFX_POKEMON_SUNFLORA		     (NUM_REGULAR_OBJ_EVENT_GFX + 191)//192
#define OBJ_EVENT_GFX_POKEMON_YANMA		         (NUM_REGULAR_OBJ_EVENT_GFX + 192)//193
#define OBJ_EVENT_GFX_POKEMON_WOOPER		     (NUM_REGULAR_OBJ_EVENT_GFX + 193)//194
#define OBJ_EVENT_GFX_POKEMON_QUAGSIRE		     (NUM_REGULAR_OBJ_EVENT_GFX + 194)//195
#define OBJ_EVENT_GFX_POKEMON_ESPEON		     (NUM_REGULAR_OBJ_EVENT_GFX + 195)//196
#define OBJ_EVENT_GFX_POKEMON_UMBREON		     (NUM_REGULAR_OBJ_EVENT_GFX + 196)//197
#define OBJ_EVENT_GFX_POKEMON_MURKROW		     (NUM_REGULAR_OBJ_EVENT_GFX + 197)//198
#define OBJ_EVENT_GFX_POKEMON_SLOWKING		     (NUM_REGULAR_OBJ_EVENT_GFX + 198)//199
#define OBJ_EVENT_GFX_POKEMON_MISDREAVUS		 (NUM_REGULAR_OBJ_EVENT_GFX + 199)//200
#define OBJ_EVENT_GFX_POKEMON_UNOWN		         (NUM_REGULAR_OBJ_EVENT_GFX + 200)//201
#define OBJ_EVENT_GFX_POKEMON_WOBBUFFET		     (NUM_REGULAR_OBJ_EVENT_GFX + 201)//202
#define OBJ_EVENT_GFX_POKEMON_GIRAFARIG		     (NUM_REGULAR_OBJ_EVENT_GFX + 202)//203
#define OBJ_EVENT_GFX_POKEMON_PINECO		     (NUM_REGULAR_OBJ_EVENT_GFX + 203)//204
#define OBJ_EVENT_GFX_POKEMON_FORRETRESS		 (NUM_REGULAR_OBJ_EVENT_GFX + 204)//205
#define OBJ_EVENT_GFX_POKEMON_DUNSPARCE		     (NUM_REGULAR_OBJ_EVENT_GFX + 205)//206
#define OBJ_EVENT_GFX_POKEMON_GLIGAR		     (NUM_REGULAR_OBJ_EVENT_GFX + 206)//207
#define OBJ_EVENT_GFX_POKEMON_STEELIX		     (NUM_REGULAR_OBJ_EVENT_GFX + 207)//208
#define OBJ_EVENT_GFX_POKEMON_SNUBBULL		     (NUM_REGULAR_OBJ_EVENT_GFX + 208)//209
#define OBJ_EVENT_GFX_POKEMON_GRANBULL		     (NUM_REGULAR_OBJ_EVENT_GFX + 209)//210
#define OBJ_EVENT_GFX_POKEMON_QWILFISH		     (NUM_REGULAR_OBJ_EVENT_GFX + 210)//211
#define OBJ_EVENT_GFX_POKEMON_SCIZOR		     (NUM_REGULAR_OBJ_EVENT_GFX + 211)//212
#define OBJ_EVENT_GFX_POKEMON_SHUCKLE		     (NUM_REGULAR_OBJ_EVENT_GFX + 212)//213
#define OBJ_EVENT_GFX_POKEMON_HERACROSS		     (NUM_REGULAR_OBJ_EVENT_GFX + 213)//214
#define OBJ_EVENT_GFX_POKEMON_SNEASEL		     (NUM_REGULAR_OBJ_EVENT_GFX + 214)//215
#define OBJ_EVENT_GFX_POKEMON_TEDDIURSA		     (NUM_REGULAR_OBJ_EVENT_GFX + 215)//216
#define OBJ_EVENT_GFX_POKEMON_URSARING		     (NUM_REGULAR_OBJ_EVENT_GFX + 216)//217
#define OBJ_EVENT_GFX_POKEMON_SLUGMA		     (NUM_REGULAR_OBJ_EVENT_GFX + 217)//218
#define OBJ_EVENT_GFX_POKEMON_MAGCARGO		     (NUM_REGULAR_OBJ_EVENT_GFX + 218)//219
#define OBJ_EVENT_GFX_POKEMON_SWINUB		     (NUM_REGULAR_OBJ_EVENT_GFX + 219)//220
#define OBJ_EVENT_GFX_POKEMON_PILOSWINE		     (NUM_REGULAR_OBJ_EVENT_GFX + 220)//221
#define OBJ_EVENT_GFX_POKEMON_CORSOLA		     (NUM_REGULAR_OBJ_EVENT_GFX + 221)//222
#define OBJ_EVENT_GFX_POKEMON_REMORAID		     (NUM_REGULAR_OBJ_EVENT_GFX + 222)//223
#define OBJ_EVENT_GFX_POKEMON_OCTILLERY		     (NUM_REGULAR_OBJ_EVENT_GFX + 223)//224
#define OBJ_EVENT_GFX_POKEMON_DELIBIRD		     (NUM_REGULAR_OBJ_EVENT_GFX + 224)//225
#define OBJ_EVENT_GFX_POKEMON_MANTINE		     (NUM_REGULAR_OBJ_EVENT_GFX + 225)//226
#define OBJ_EVENT_GFX_POKEMON_SKARMORY		     (NUM_REGULAR_OBJ_EVENT_GFX + 226)//227
#define OBJ_EVENT_GFX_POKEMON_HOUNDOUR		     (NUM_REGULAR_OBJ_EVENT_GFX + 227)//228
#define OBJ_EVENT_GFX_POKEMON_HOUNDOOM		     (NUM_REGULAR_OBJ_EVENT_GFX + 228)//229
#define OBJ_EVENT_GFX_POKEMON_KINGDRA		     (NUM_REGULAR_OBJ_EVENT_GFX + 229)//230
#define OBJ_EVENT_GFX_POKEMON_PHANPY		     (NUM_REGULAR_OBJ_EVENT_GFX + 230)//231
#define OBJ_EVENT_GFX_POKEMON_DONPHAN		     (NUM_REGULAR_OBJ_EVENT_GFX + 231)//232
#define OBJ_EVENT_GFX_POKEMON_PORYGON_2		     (NUM_REGULAR_OBJ_EVENT_GFX + 232)//233
#define OBJ_EVENT_GFX_POKEMON_STANTLER		     (NUM_REGULAR_OBJ_EVENT_GFX + 233)//234
#define OBJ_EVENT_GFX_POKEMON_SMEARGLE		     (NUM_REGULAR_OBJ_EVENT_GFX + 234)//235
#define OBJ_EVENT_GFX_POKEMON_TYROGUE		     (NUM_REGULAR_OBJ_EVENT_GFX + 235)//236
#define OBJ_EVENT_GFX_POKEMON_HITMONTOP		     (NUM_REGULAR_OBJ_EVENT_GFX + 236)//237
#define OBJ_EVENT_GFX_POKEMON_SMOOCHUM		     (NUM_REGULAR_OBJ_EVENT_GFX + 237)//238
#define OBJ_EVENT_GFX_POKEMON_ELEKID		     (NUM_REGULAR_OBJ_EVENT_GFX + 238)//239
#define OBJ_EVENT_GFX_POKEMON_MAGBY		         (NUM_REGULAR_OBJ_EVENT_GFX + 239)//240
#define OBJ_EVENT_GFX_POKEMON_MILTANK		     (NUM_REGULAR_OBJ_EVENT_GFX + 240)//241
#define OBJ_EVENT_GFX_POKEMON_BLISSEY		     (NUM_REGULAR_OBJ_EVENT_GFX + 241)//242
#define OBJ_EVENT_GFX_POKEMON_RAIKOU		     (NUM_REGULAR_OBJ_EVENT_GFX + 242)//243
#define OBJ_EVENT_GFX_POKEMON_ENTEI		         (NUM_REGULAR_OBJ_EVENT_GFX + 243)//244
#define OBJ_EVENT_GFX_POKEMON_SUICUNE		     (NUM_REGULAR_OBJ_EVENT_GFX + 244)//245
#define OBJ_EVENT_GFX_POKEMON_LARVITAR		     (NUM_REGULAR_OBJ_EVENT_GFX + 245)//246
#define OBJ_EVENT_GFX_POKEMON_PUPITAR		     (NUM_REGULAR_OBJ_EVENT_GFX + 246)//247
#define OBJ_EVENT_GFX_POKEMON_TYRANITAR		     (NUM_REGULAR_OBJ_EVENT_GFX + 247)//248
#define OBJ_EVENT_GFX_POKEMON_LUGIA		         (NUM_REGULAR_OBJ_EVENT_GFX + 248)//249
#define OBJ_EVENT_GFX_POKEMON_HO_OH		         (NUM_REGULAR_OBJ_EVENT_GFX + 249)//250
#define OBJ_EVENT_GFX_POKEMON_CELEBI		     (NUM_REGULAR_OBJ_EVENT_GFX + 250)//251

//Gen 3 (135
#define OBJ_EVENT_GFX_POKEMON_252		(NUM_REGULAR_OBJ_EVENT_GFX + 251)//252
#define OBJ_EVENT_GFX_POKEMON_253		(NUM_REGULAR_OBJ_EVENT_GFX + 252)//253
#define OBJ_EVENT_GFX_POKEMON_254		(NUM_REGULAR_OBJ_EVENT_GFX + 253)//254
#define OBJ_EVENT_GFX_POKEMON_255		(NUM_REGULAR_OBJ_EVENT_GFX + 254)//255
#define OBJ_EVENT_GFX_POKEMON_256		(NUM_REGULAR_OBJ_EVENT_GFX + 255)//256
#define OBJ_EVENT_GFX_POKEMON_257		(NUM_REGULAR_OBJ_EVENT_GFX + 256)//257
#define OBJ_EVENT_GFX_POKEMON_258		(NUM_REGULAR_OBJ_EVENT_GFX + 257)//258
#define OBJ_EVENT_GFX_POKEMON_259		(NUM_REGULAR_OBJ_EVENT_GFX + 258)//259
#define OBJ_EVENT_GFX_POKEMON_260		(NUM_REGULAR_OBJ_EVENT_GFX + 259)//260
#define OBJ_EVENT_GFX_POKEMON_261		(NUM_REGULAR_OBJ_EVENT_GFX + 260)//261
#define OBJ_EVENT_GFX_POKEMON_262		(NUM_REGULAR_OBJ_EVENT_GFX + 261)//262
#define OBJ_EVENT_GFX_POKEMON_263		(NUM_REGULAR_OBJ_EVENT_GFX + 262)//263
#define OBJ_EVENT_GFX_POKEMON_264		(NUM_REGULAR_OBJ_EVENT_GFX + 263)//264
#define OBJ_EVENT_GFX_POKEMON_265		(NUM_REGULAR_OBJ_EVENT_GFX + 264)//265
#define OBJ_EVENT_GFX_POKEMON_266		(NUM_REGULAR_OBJ_EVENT_GFX + 265)//266
#define OBJ_EVENT_GFX_POKEMON_267		(NUM_REGULAR_OBJ_EVENT_GFX + 266)//267
#define OBJ_EVENT_GFX_POKEMON_268		(NUM_REGULAR_OBJ_EVENT_GFX + 267)//268
#define OBJ_EVENT_GFX_POKEMON_269		(NUM_REGULAR_OBJ_EVENT_GFX + 268)//269
#define OBJ_EVENT_GFX_POKEMON_270		(NUM_REGULAR_OBJ_EVENT_GFX + 269)//270
#define OBJ_EVENT_GFX_POKEMON_271		(NUM_REGULAR_OBJ_EVENT_GFX + 270)//271
#define OBJ_EVENT_GFX_POKEMON_272		(NUM_REGULAR_OBJ_EVENT_GFX + 271)//272
#define OBJ_EVENT_GFX_POKEMON_273		(NUM_REGULAR_OBJ_EVENT_GFX + 272)//273
#define OBJ_EVENT_GFX_POKEMON_274		(NUM_REGULAR_OBJ_EVENT_GFX + 273)//274
#define OBJ_EVENT_GFX_POKEMON_275		(NUM_REGULAR_OBJ_EVENT_GFX + 274)//275
#define OBJ_EVENT_GFX_POKEMON_276		(NUM_REGULAR_OBJ_EVENT_GFX + 275)//276
#define OBJ_EVENT_GFX_POKEMON_277		(NUM_REGULAR_OBJ_EVENT_GFX + 276)//277
#define OBJ_EVENT_GFX_POKEMON_278		(NUM_REGULAR_OBJ_EVENT_GFX + 277)//278
#define OBJ_EVENT_GFX_POKEMON_279		(NUM_REGULAR_OBJ_EVENT_GFX + 278)//279
#define OBJ_EVENT_GFX_POKEMON_280		(NUM_REGULAR_OBJ_EVENT_GFX + 279)//280
#define OBJ_EVENT_GFX_POKEMON_281		(NUM_REGULAR_OBJ_EVENT_GFX + 280)//281
#define OBJ_EVENT_GFX_POKEMON_282		(NUM_REGULAR_OBJ_EVENT_GFX + 281)//282
#define OBJ_EVENT_GFX_POKEMON_283		(NUM_REGULAR_OBJ_EVENT_GFX + 282)//283
#define OBJ_EVENT_GFX_POKEMON_284		(NUM_REGULAR_OBJ_EVENT_GFX + 283)//284
#define OBJ_EVENT_GFX_POKEMON_285		(NUM_REGULAR_OBJ_EVENT_GFX + 284)//285
#define OBJ_EVENT_GFX_POKEMON_286		(NUM_REGULAR_OBJ_EVENT_GFX + 285)//286
#define OBJ_EVENT_GFX_POKEMON_287		(NUM_REGULAR_OBJ_EVENT_GFX + 286)//287
#define OBJ_EVENT_GFX_POKEMON_288		(NUM_REGULAR_OBJ_EVENT_GFX + 287)//288
#define OBJ_EVENT_GFX_POKEMON_289		(NUM_REGULAR_OBJ_EVENT_GFX + 288)//289
#define OBJ_EVENT_GFX_POKEMON_290		(NUM_REGULAR_OBJ_EVENT_GFX + 289)//290
#define OBJ_EVENT_GFX_POKEMON_291		(NUM_REGULAR_OBJ_EVENT_GFX + 290)//291
#define OBJ_EVENT_GFX_POKEMON_292		(NUM_REGULAR_OBJ_EVENT_GFX + 291)//292
#define OBJ_EVENT_GFX_POKEMON_293		(NUM_REGULAR_OBJ_EVENT_GFX + 292)//293
#define OBJ_EVENT_GFX_POKEMON_294		(NUM_REGULAR_OBJ_EVENT_GFX + 293)//294
#define OBJ_EVENT_GFX_POKEMON_295		(NUM_REGULAR_OBJ_EVENT_GFX + 294)//295
#define OBJ_EVENT_GFX_POKEMON_296		(NUM_REGULAR_OBJ_EVENT_GFX + 295)//296
#define OBJ_EVENT_GFX_POKEMON_297		(NUM_REGULAR_OBJ_EVENT_GFX + 296)//297
#define OBJ_EVENT_GFX_POKEMON_298		(NUM_REGULAR_OBJ_EVENT_GFX + 297)//298
#define OBJ_EVENT_GFX_POKEMON_299		(NUM_REGULAR_OBJ_EVENT_GFX + 298)//299
#define OBJ_EVENT_GFX_POKEMON_300		(NUM_REGULAR_OBJ_EVENT_GFX + 299)//300
#define OBJ_EVENT_GFX_POKEMON_301		(NUM_REGULAR_OBJ_EVENT_GFX + 300)//301
#define OBJ_EVENT_GFX_POKEMON_302		(NUM_REGULAR_OBJ_EVENT_GFX + 301)//302
#define OBJ_EVENT_GFX_POKEMON_303		(NUM_REGULAR_OBJ_EVENT_GFX + 302)//303
#define OBJ_EVENT_GFX_POKEMON_304		(NUM_REGULAR_OBJ_EVENT_GFX + 303)//304
#define OBJ_EVENT_GFX_POKEMON_305		(NUM_REGULAR_OBJ_EVENT_GFX + 304)//305
#define OBJ_EVENT_GFX_POKEMON_306		(NUM_REGULAR_OBJ_EVENT_GFX + 305)//306
#define OBJ_EVENT_GFX_POKEMON_307		(NUM_REGULAR_OBJ_EVENT_GFX + 306)//307
#define OBJ_EVENT_GFX_POKEMON_308		(NUM_REGULAR_OBJ_EVENT_GFX + 307)//308
#define OBJ_EVENT_GFX_POKEMON_309		(NUM_REGULAR_OBJ_EVENT_GFX + 308)//309
#define OBJ_EVENT_GFX_POKEMON_310		(NUM_REGULAR_OBJ_EVENT_GFX + 309)//310
#define OBJ_EVENT_GFX_POKEMON_311		(NUM_REGULAR_OBJ_EVENT_GFX + 310)//311
#define OBJ_EVENT_GFX_POKEMON_312		(NUM_REGULAR_OBJ_EVENT_GFX + 311)//312
#define OBJ_EVENT_GFX_POKEMON_313		(NUM_REGULAR_OBJ_EVENT_GFX + 312)//313
#define OBJ_EVENT_GFX_POKEMON_314		(NUM_REGULAR_OBJ_EVENT_GFX + 313)//314
#define OBJ_EVENT_GFX_POKEMON_315		(NUM_REGULAR_OBJ_EVENT_GFX + 314)//315
#define OBJ_EVENT_GFX_POKEMON_316		(NUM_REGULAR_OBJ_EVENT_GFX + 315)//316
#define OBJ_EVENT_GFX_POKEMON_317		(NUM_REGULAR_OBJ_EVENT_GFX + 316)//317
#define OBJ_EVENT_GFX_POKEMON_318		(NUM_REGULAR_OBJ_EVENT_GFX + 317)//318
#define OBJ_EVENT_GFX_POKEMON_319		(NUM_REGULAR_OBJ_EVENT_GFX + 318)//319
#define OBJ_EVENT_GFX_POKEMON_320		(NUM_REGULAR_OBJ_EVENT_GFX + 319)//320
#define OBJ_EVENT_GFX_POKEMON_321		(NUM_REGULAR_OBJ_EVENT_GFX + 320)//321
#define OBJ_EVENT_GFX_POKEMON_322		(NUM_REGULAR_OBJ_EVENT_GFX + 321)//322
#define OBJ_EVENT_GFX_POKEMON_323		(NUM_REGULAR_OBJ_EVENT_GFX + 322)//323
#define OBJ_EVENT_GFX_POKEMON_324		(NUM_REGULAR_OBJ_EVENT_GFX + 323)//324
#define OBJ_EVENT_GFX_POKEMON_325		(NUM_REGULAR_OBJ_EVENT_GFX + 324)//325
#define OBJ_EVENT_GFX_POKEMON_326		(NUM_REGULAR_OBJ_EVENT_GFX + 325)//326
#define OBJ_EVENT_GFX_POKEMON_327		(NUM_REGULAR_OBJ_EVENT_GFX + 326)//327
#define OBJ_EVENT_GFX_POKEMON_328		(NUM_REGULAR_OBJ_EVENT_GFX + 327)//328
#define OBJ_EVENT_GFX_POKEMON_329		(NUM_REGULAR_OBJ_EVENT_GFX + 328)//329
#define OBJ_EVENT_GFX_POKEMON_330		(NUM_REGULAR_OBJ_EVENT_GFX + 329)//330
#define OBJ_EVENT_GFX_POKEMON_331		(NUM_REGULAR_OBJ_EVENT_GFX + 330)//331
#define OBJ_EVENT_GFX_POKEMON_332		(NUM_REGULAR_OBJ_EVENT_GFX + 331)//332
#define OBJ_EVENT_GFX_POKEMON_333		(NUM_REGULAR_OBJ_EVENT_GFX + 332)//333
#define OBJ_EVENT_GFX_POKEMON_334		(NUM_REGULAR_OBJ_EVENT_GFX + 333)//334
#define OBJ_EVENT_GFX_POKEMON_335		(NUM_REGULAR_OBJ_EVENT_GFX + 334)//335
#define OBJ_EVENT_GFX_POKEMON_336		(NUM_REGULAR_OBJ_EVENT_GFX + 335)//336
#define OBJ_EVENT_GFX_POKEMON_337		(NUM_REGULAR_OBJ_EVENT_GFX + 336)//337
#define OBJ_EVENT_GFX_POKEMON_338		(NUM_REGULAR_OBJ_EVENT_GFX + 337)//338
#define OBJ_EVENT_GFX_POKEMON_339		(NUM_REGULAR_OBJ_EVENT_GFX + 338)//339
#define OBJ_EVENT_GFX_POKEMON_340		(NUM_REGULAR_OBJ_EVENT_GFX + 339)//340
#define OBJ_EVENT_GFX_POKEMON_341		(NUM_REGULAR_OBJ_EVENT_GFX + 340)//341
#define OBJ_EVENT_GFX_POKEMON_342		(NUM_REGULAR_OBJ_EVENT_GFX + 341)//342
#define OBJ_EVENT_GFX_POKEMON_343		(NUM_REGULAR_OBJ_EVENT_GFX + 342)//343
#define OBJ_EVENT_GFX_POKEMON_344		(NUM_REGULAR_OBJ_EVENT_GFX + 343)//344
#define OBJ_EVENT_GFX_POKEMON_345		(NUM_REGULAR_OBJ_EVENT_GFX + 344)//345
#define OBJ_EVENT_GFX_POKEMON_346		(NUM_REGULAR_OBJ_EVENT_GFX + 345)//346
#define OBJ_EVENT_GFX_POKEMON_347		(NUM_REGULAR_OBJ_EVENT_GFX + 346)//347
#define OBJ_EVENT_GFX_POKEMON_348		(NUM_REGULAR_OBJ_EVENT_GFX + 347)//348
#define OBJ_EVENT_GFX_POKEMON_349		(NUM_REGULAR_OBJ_EVENT_GFX + 348)//349
#define OBJ_EVENT_GFX_POKEMON_350		(NUM_REGULAR_OBJ_EVENT_GFX + 349)//350
#define OBJ_EVENT_GFX_POKEMON_351		(NUM_REGULAR_OBJ_EVENT_GFX + 350)//351
#define OBJ_EVENT_GFX_POKEMON_352		(NUM_REGULAR_OBJ_EVENT_GFX + 351)//352
#define OBJ_EVENT_GFX_POKEMON_353		(NUM_REGULAR_OBJ_EVENT_GFX + 352)//353
#define OBJ_EVENT_GFX_POKEMON_354		(NUM_REGULAR_OBJ_EVENT_GFX + 353)//354
#define OBJ_EVENT_GFX_POKEMON_355		(NUM_REGULAR_OBJ_EVENT_GFX + 354)//355
#define OBJ_EVENT_GFX_POKEMON_356		(NUM_REGULAR_OBJ_EVENT_GFX + 355)//356
#define OBJ_EVENT_GFX_POKEMON_357		(NUM_REGULAR_OBJ_EVENT_GFX + 356)//357
#define OBJ_EVENT_GFX_POKEMON_358		(NUM_REGULAR_OBJ_EVENT_GFX + 357)//358
#define OBJ_EVENT_GFX_POKEMON_359		(NUM_REGULAR_OBJ_EVENT_GFX + 358)//359
#define OBJ_EVENT_GFX_POKEMON_360		(NUM_REGULAR_OBJ_EVENT_GFX + 359)//360
#define OBJ_EVENT_GFX_POKEMON_361		(NUM_REGULAR_OBJ_EVENT_GFX + 360)//361
#define OBJ_EVENT_GFX_POKEMON_362		(NUM_REGULAR_OBJ_EVENT_GFX + 361)//362
#define OBJ_EVENT_GFX_POKEMON_363		(NUM_REGULAR_OBJ_EVENT_GFX + 362)//363
#define OBJ_EVENT_GFX_POKEMON_364		(NUM_REGULAR_OBJ_EVENT_GFX + 363)//364
#define OBJ_EVENT_GFX_POKEMON_365		(NUM_REGULAR_OBJ_EVENT_GFX + 364)//365
#define OBJ_EVENT_GFX_POKEMON_366		(NUM_REGULAR_OBJ_EVENT_GFX + 365)//366
#define OBJ_EVENT_GFX_POKEMON_367		(NUM_REGULAR_OBJ_EVENT_GFX + 366)//367
#define OBJ_EVENT_GFX_POKEMON_368		(NUM_REGULAR_OBJ_EVENT_GFX + 367)//368
#define OBJ_EVENT_GFX_POKEMON_369		(NUM_REGULAR_OBJ_EVENT_GFX + 368)//369
#define OBJ_EVENT_GFX_POKEMON_370		(NUM_REGULAR_OBJ_EVENT_GFX + 369)//370
#define OBJ_EVENT_GFX_POKEMON_371		(NUM_REGULAR_OBJ_EVENT_GFX + 370)//371
#define OBJ_EVENT_GFX_POKEMON_372		(NUM_REGULAR_OBJ_EVENT_GFX + 371)//372
#define OBJ_EVENT_GFX_POKEMON_373		(NUM_REGULAR_OBJ_EVENT_GFX + 372)//373
#define OBJ_EVENT_GFX_POKEMON_374		(NUM_REGULAR_OBJ_EVENT_GFX + 373)//374
#define OBJ_EVENT_GFX_POKEMON_375		(NUM_REGULAR_OBJ_EVENT_GFX + 374)//375
#define OBJ_EVENT_GFX_POKEMON_376		(NUM_REGULAR_OBJ_EVENT_GFX + 375)//376
#define OBJ_EVENT_GFX_POKEMON_377		(NUM_REGULAR_OBJ_EVENT_GFX + 376)//377
#define OBJ_EVENT_GFX_POKEMON_378		(NUM_REGULAR_OBJ_EVENT_GFX + 377)//378
#define OBJ_EVENT_GFX_POKEMON_379		(NUM_REGULAR_OBJ_EVENT_GFX + 378)//379
#define OBJ_EVENT_GFX_POKEMON_380		(NUM_REGULAR_OBJ_EVENT_GFX + 379)//380
#define OBJ_EVENT_GFX_POKEMON_381		(NUM_REGULAR_OBJ_EVENT_GFX + 380)//381
#define OBJ_EVENT_GFX_POKEMON_382		(NUM_REGULAR_OBJ_EVENT_GFX + 381)//382
#define OBJ_EVENT_GFX_POKEMON_383		(NUM_REGULAR_OBJ_EVENT_GFX + 382)//383
#define OBJ_EVENT_GFX_POKEMON_384		(NUM_REGULAR_OBJ_EVENT_GFX + 383)//384
#define OBJ_EVENT_GFX_POKEMON_385		(NUM_REGULAR_OBJ_EVENT_GFX + 384)//385
#define OBJ_EVENT_GFX_POKEMON_386		(NUM_REGULAR_OBJ_EVENT_GFX + 385)//386

//Gen 4 (107
#define OBJ_EVENT_GFX_POKEMON_387		(NUM_REGULAR_OBJ_EVENT_GFX + 386)//387
#define OBJ_EVENT_GFX_POKEMON_388		(NUM_REGULAR_OBJ_EVENT_GFX + 387)//388
#define OBJ_EVENT_GFX_POKEMON_389		(NUM_REGULAR_OBJ_EVENT_GFX + 388)//389
#define OBJ_EVENT_GFX_POKEMON_390		(NUM_REGULAR_OBJ_EVENT_GFX + 389)//390
#define OBJ_EVENT_GFX_POKEMON_391		(NUM_REGULAR_OBJ_EVENT_GFX + 390)//391
#define OBJ_EVENT_GFX_POKEMON_392		(NUM_REGULAR_OBJ_EVENT_GFX + 391)//392
#define OBJ_EVENT_GFX_POKEMON_393		(NUM_REGULAR_OBJ_EVENT_GFX + 392)//393
#define OBJ_EVENT_GFX_POKEMON_394		(NUM_REGULAR_OBJ_EVENT_GFX + 393)//394
#define OBJ_EVENT_GFX_POKEMON_395		(NUM_REGULAR_OBJ_EVENT_GFX + 394)//395
#define OBJ_EVENT_GFX_POKEMON_396		(NUM_REGULAR_OBJ_EVENT_GFX + 395)//396
#define OBJ_EVENT_GFX_POKEMON_397		(NUM_REGULAR_OBJ_EVENT_GFX + 396)//397
#define OBJ_EVENT_GFX_POKEMON_398		(NUM_REGULAR_OBJ_EVENT_GFX + 397)//398
#define OBJ_EVENT_GFX_POKEMON_399		(NUM_REGULAR_OBJ_EVENT_GFX + 398)//399
#define OBJ_EVENT_GFX_POKEMON_400		(NUM_REGULAR_OBJ_EVENT_GFX + 399)//400
#define OBJ_EVENT_GFX_POKEMON_401		(NUM_REGULAR_OBJ_EVENT_GFX + 400)//401
#define OBJ_EVENT_GFX_POKEMON_402		(NUM_REGULAR_OBJ_EVENT_GFX + 401)//402
#define OBJ_EVENT_GFX_POKEMON_403		(NUM_REGULAR_OBJ_EVENT_GFX + 402)//403
#define OBJ_EVENT_GFX_POKEMON_404		(NUM_REGULAR_OBJ_EVENT_GFX + 403)//404
#define OBJ_EVENT_GFX_POKEMON_405		(NUM_REGULAR_OBJ_EVENT_GFX + 404)//405
#define OBJ_EVENT_GFX_POKEMON_406		(NUM_REGULAR_OBJ_EVENT_GFX + 405)//406
#define OBJ_EVENT_GFX_POKEMON_407		(NUM_REGULAR_OBJ_EVENT_GFX + 406)//407
#define OBJ_EVENT_GFX_POKEMON_408		(NUM_REGULAR_OBJ_EVENT_GFX + 407)//408
#define OBJ_EVENT_GFX_POKEMON_409		(NUM_REGULAR_OBJ_EVENT_GFX + 408)//409
#define OBJ_EVENT_GFX_POKEMON_410		(NUM_REGULAR_OBJ_EVENT_GFX + 409)//410
#define OBJ_EVENT_GFX_POKEMON_411		(NUM_REGULAR_OBJ_EVENT_GFX + 410)//411
#define OBJ_EVENT_GFX_POKEMON_412		(NUM_REGULAR_OBJ_EVENT_GFX + 411)//412
#define OBJ_EVENT_GFX_POKEMON_413		(NUM_REGULAR_OBJ_EVENT_GFX + 412)//413
#define OBJ_EVENT_GFX_POKEMON_414		(NUM_REGULAR_OBJ_EVENT_GFX + 413)//414
#define OBJ_EVENT_GFX_POKEMON_415		(NUM_REGULAR_OBJ_EVENT_GFX + 414)//415
#define OBJ_EVENT_GFX_POKEMON_416		(NUM_REGULAR_OBJ_EVENT_GFX + 415)//416
#define OBJ_EVENT_GFX_POKEMON_417		(NUM_REGULAR_OBJ_EVENT_GFX + 416)//417
#define OBJ_EVENT_GFX_POKEMON_418		(NUM_REGULAR_OBJ_EVENT_GFX + 417)//418
#define OBJ_EVENT_GFX_POKEMON_419		(NUM_REGULAR_OBJ_EVENT_GFX + 418)//419
#define OBJ_EVENT_GFX_POKEMON_420		(NUM_REGULAR_OBJ_EVENT_GFX + 419)//420
#define OBJ_EVENT_GFX_POKEMON_421		(NUM_REGULAR_OBJ_EVENT_GFX + 420)//421
#define OBJ_EVENT_GFX_POKEMON_422		(NUM_REGULAR_OBJ_EVENT_GFX + 421)//422
#define OBJ_EVENT_GFX_POKEMON_423		(NUM_REGULAR_OBJ_EVENT_GFX + 422)//423
#define OBJ_EVENT_GFX_POKEMON_424		(NUM_REGULAR_OBJ_EVENT_GFX + 423)//424
#define OBJ_EVENT_GFX_POKEMON_425		(NUM_REGULAR_OBJ_EVENT_GFX + 424)//425
#define OBJ_EVENT_GFX_POKEMON_426		(NUM_REGULAR_OBJ_EVENT_GFX + 425)//426
#define OBJ_EVENT_GFX_POKEMON_427		(NUM_REGULAR_OBJ_EVENT_GFX + 426)//427
#define OBJ_EVENT_GFX_POKEMON_428		(NUM_REGULAR_OBJ_EVENT_GFX + 427)//428
#define OBJ_EVENT_GFX_POKEMON_429		(NUM_REGULAR_OBJ_EVENT_GFX + 428)//429
#define OBJ_EVENT_GFX_POKEMON_430		(NUM_REGULAR_OBJ_EVENT_GFX + 429)//430
#define OBJ_EVENT_GFX_POKEMON_431		(NUM_REGULAR_OBJ_EVENT_GFX + 430)//431
#define OBJ_EVENT_GFX_POKEMON_432		(NUM_REGULAR_OBJ_EVENT_GFX + 431)//432
#define OBJ_EVENT_GFX_POKEMON_433		(NUM_REGULAR_OBJ_EVENT_GFX + 432)//433
#define OBJ_EVENT_GFX_POKEMON_434		(NUM_REGULAR_OBJ_EVENT_GFX + 433)//434
#define OBJ_EVENT_GFX_POKEMON_435		(NUM_REGULAR_OBJ_EVENT_GFX + 434)//435
#define OBJ_EVENT_GFX_POKEMON_436		(NUM_REGULAR_OBJ_EVENT_GFX + 435)//436
#define OBJ_EVENT_GFX_POKEMON_437		(NUM_REGULAR_OBJ_EVENT_GFX + 436)//437
#define OBJ_EVENT_GFX_POKEMON_438		(NUM_REGULAR_OBJ_EVENT_GFX + 437)//438
#define OBJ_EVENT_GFX_POKEMON_439		(NUM_REGULAR_OBJ_EVENT_GFX + 438)//439
#define OBJ_EVENT_GFX_POKEMON_440		(NUM_REGULAR_OBJ_EVENT_GFX + 439)//440
#define OBJ_EVENT_GFX_POKEMON_441		(NUM_REGULAR_OBJ_EVENT_GFX + 440)//441
#define OBJ_EVENT_GFX_POKEMON_442		(NUM_REGULAR_OBJ_EVENT_GFX + 441)//442
#define OBJ_EVENT_GFX_POKEMON_443		(NUM_REGULAR_OBJ_EVENT_GFX + 442)//443
#define OBJ_EVENT_GFX_POKEMON_444		(NUM_REGULAR_OBJ_EVENT_GFX + 443)//444
#define OBJ_EVENT_GFX_POKEMON_445		(NUM_REGULAR_OBJ_EVENT_GFX + 444)//445
#define OBJ_EVENT_GFX_POKEMON_446		(NUM_REGULAR_OBJ_EVENT_GFX + 445)//446
#define OBJ_EVENT_GFX_POKEMON_447		(NUM_REGULAR_OBJ_EVENT_GFX + 446)//447
#define OBJ_EVENT_GFX_POKEMON_448		(NUM_REGULAR_OBJ_EVENT_GFX + 447)//448
#define OBJ_EVENT_GFX_POKEMON_449		(NUM_REGULAR_OBJ_EVENT_GFX + 448)//449
#define OBJ_EVENT_GFX_POKEMON_450		(NUM_REGULAR_OBJ_EVENT_GFX + 449)//450
#define OBJ_EVENT_GFX_POKEMON_451		(NUM_REGULAR_OBJ_EVENT_GFX + 450)//451
#define OBJ_EVENT_GFX_POKEMON_452		(NUM_REGULAR_OBJ_EVENT_GFX + 451)//452
#define OBJ_EVENT_GFX_POKEMON_453		(NUM_REGULAR_OBJ_EVENT_GFX + 452)//453
#define OBJ_EVENT_GFX_POKEMON_454		(NUM_REGULAR_OBJ_EVENT_GFX + 453)//454
#define OBJ_EVENT_GFX_POKEMON_455		(NUM_REGULAR_OBJ_EVENT_GFX + 454)//455
#define OBJ_EVENT_GFX_POKEMON_456		(NUM_REGULAR_OBJ_EVENT_GFX + 455)//456
#define OBJ_EVENT_GFX_POKEMON_457		(NUM_REGULAR_OBJ_EVENT_GFX + 456)//457
#define OBJ_EVENT_GFX_POKEMON_458		(NUM_REGULAR_OBJ_EVENT_GFX + 457)//458
#define OBJ_EVENT_GFX_POKEMON_459		(NUM_REGULAR_OBJ_EVENT_GFX + 458)//459
#define OBJ_EVENT_GFX_POKEMON_460		(NUM_REGULAR_OBJ_EVENT_GFX + 459)//460
#define OBJ_EVENT_GFX_POKEMON_461		(NUM_REGULAR_OBJ_EVENT_GFX + 460)//461
#define OBJ_EVENT_GFX_POKEMON_462		(NUM_REGULAR_OBJ_EVENT_GFX + 461)//462
#define OBJ_EVENT_GFX_POKEMON_463		(NUM_REGULAR_OBJ_EVENT_GFX + 462)//463
#define OBJ_EVENT_GFX_POKEMON_464		(NUM_REGULAR_OBJ_EVENT_GFX + 463)//464
#define OBJ_EVENT_GFX_POKEMON_465		(NUM_REGULAR_OBJ_EVENT_GFX + 464)//465
#define OBJ_EVENT_GFX_POKEMON_466		(NUM_REGULAR_OBJ_EVENT_GFX + 465)//466
#define OBJ_EVENT_GFX_POKEMON_467		(NUM_REGULAR_OBJ_EVENT_GFX + 466)//467
#define OBJ_EVENT_GFX_POKEMON_468		(NUM_REGULAR_OBJ_EVENT_GFX + 467)//468
#define OBJ_EVENT_GFX_POKEMON_469		(NUM_REGULAR_OBJ_EVENT_GFX + 468)//469
#define OBJ_EVENT_GFX_POKEMON_470		(NUM_REGULAR_OBJ_EVENT_GFX + 469)//470
#define OBJ_EVENT_GFX_POKEMON_471		(NUM_REGULAR_OBJ_EVENT_GFX + 470)//471
#define OBJ_EVENT_GFX_POKEMON_472		(NUM_REGULAR_OBJ_EVENT_GFX + 471)//472
#define OBJ_EVENT_GFX_POKEMON_473		(NUM_REGULAR_OBJ_EVENT_GFX + 472)//473
#define OBJ_EVENT_GFX_POKEMON_474		(NUM_REGULAR_OBJ_EVENT_GFX + 473)//474
#define OBJ_EVENT_GFX_POKEMON_475		(NUM_REGULAR_OBJ_EVENT_GFX + 474)//475
#define OBJ_EVENT_GFX_POKEMON_476		(NUM_REGULAR_OBJ_EVENT_GFX + 475)//476
#define OBJ_EVENT_GFX_POKEMON_477		(NUM_REGULAR_OBJ_EVENT_GFX + 476)//477
#define OBJ_EVENT_GFX_POKEMON_478		(NUM_REGULAR_OBJ_EVENT_GFX + 477)//478
#define OBJ_EVENT_GFX_POKEMON_479		(NUM_REGULAR_OBJ_EVENT_GFX + 478)//479
#define OBJ_EVENT_GFX_POKEMON_480		(NUM_REGULAR_OBJ_EVENT_GFX + 479)//480
#define OBJ_EVENT_GFX_POKEMON_481		(NUM_REGULAR_OBJ_EVENT_GFX + 480)//481
#define OBJ_EVENT_GFX_POKEMON_482		(NUM_REGULAR_OBJ_EVENT_GFX + 481)//482
#define OBJ_EVENT_GFX_POKEMON_483		(NUM_REGULAR_OBJ_EVENT_GFX + 482)//483
#define OBJ_EVENT_GFX_POKEMON_484		(NUM_REGULAR_OBJ_EVENT_GFX + 483)//484
#define OBJ_EVENT_GFX_POKEMON_485		(NUM_REGULAR_OBJ_EVENT_GFX + 484)//485
#define OBJ_EVENT_GFX_POKEMON_486		(NUM_REGULAR_OBJ_EVENT_GFX + 485)//486
#define OBJ_EVENT_GFX_POKEMON_487		(NUM_REGULAR_OBJ_EVENT_GFX + 486)//487
#define OBJ_EVENT_GFX_POKEMON_488		(NUM_REGULAR_OBJ_EVENT_GFX + 487)//488
#define OBJ_EVENT_GFX_POKEMON_489		(NUM_REGULAR_OBJ_EVENT_GFX + 488)//489
#define OBJ_EVENT_GFX_POKEMON_490		(NUM_REGULAR_OBJ_EVENT_GFX + 489)//490
#define OBJ_EVENT_GFX_POKEMON_491		(NUM_REGULAR_OBJ_EVENT_GFX + 490)//491
#define OBJ_EVENT_GFX_POKEMON_492		(NUM_REGULAR_OBJ_EVENT_GFX + 491)//492
#define OBJ_EVENT_GFX_POKEMON_493		(NUM_REGULAR_OBJ_EVENT_GFX + 492)//493

//Gen 5 (156
#define OBJ_EVENT_GFX_POKEMON_494		(NUM_REGULAR_OBJ_EVENT_GFX + 493)//494
#define OBJ_EVENT_GFX_POKEMON_495		(NUM_REGULAR_OBJ_EVENT_GFX + 494)//495
#define OBJ_EVENT_GFX_POKEMON_496		(NUM_REGULAR_OBJ_EVENT_GFX + 495)//496
#define OBJ_EVENT_GFX_POKEMON_497		(NUM_REGULAR_OBJ_EVENT_GFX + 496)//497
#define OBJ_EVENT_GFX_POKEMON_498		(NUM_REGULAR_OBJ_EVENT_GFX + 497)//498
#define OBJ_EVENT_GFX_POKEMON_499		(NUM_REGULAR_OBJ_EVENT_GFX + 498)//499
#define OBJ_EVENT_GFX_POKEMON_500		(NUM_REGULAR_OBJ_EVENT_GFX + 499)//500
#define OBJ_EVENT_GFX_POKEMON_501		(NUM_REGULAR_OBJ_EVENT_GFX + 500)//501
#define OBJ_EVENT_GFX_POKEMON_502		(NUM_REGULAR_OBJ_EVENT_GFX + 501)//502
#define OBJ_EVENT_GFX_POKEMON_503		(NUM_REGULAR_OBJ_EVENT_GFX + 502)//503
#define OBJ_EVENT_GFX_POKEMON_504		(NUM_REGULAR_OBJ_EVENT_GFX + 503)//504
#define OBJ_EVENT_GFX_POKEMON_505		(NUM_REGULAR_OBJ_EVENT_GFX + 504)//505
#define OBJ_EVENT_GFX_POKEMON_506		(NUM_REGULAR_OBJ_EVENT_GFX + 505)//506
#define OBJ_EVENT_GFX_POKEMON_507		(NUM_REGULAR_OBJ_EVENT_GFX + 506)//507
#define OBJ_EVENT_GFX_POKEMON_508		(NUM_REGULAR_OBJ_EVENT_GFX + 507)//508
#define OBJ_EVENT_GFX_POKEMON_509		(NUM_REGULAR_OBJ_EVENT_GFX + 508)//509
#define OBJ_EVENT_GFX_POKEMON_510		(NUM_REGULAR_OBJ_EVENT_GFX + 509)//510
#define OBJ_EVENT_GFX_POKEMON_511		(NUM_REGULAR_OBJ_EVENT_GFX + 510)//511
#define OBJ_EVENT_GFX_POKEMON_512		(NUM_REGULAR_OBJ_EVENT_GFX + 511)//512
#define OBJ_EVENT_GFX_POKEMON_513		(NUM_REGULAR_OBJ_EVENT_GFX + 512)//513
#define OBJ_EVENT_GFX_POKEMON_514		(NUM_REGULAR_OBJ_EVENT_GFX + 513)//514
#define OBJ_EVENT_GFX_POKEMON_515		(NUM_REGULAR_OBJ_EVENT_GFX + 514)//515
#define OBJ_EVENT_GFX_POKEMON_516		(NUM_REGULAR_OBJ_EVENT_GFX + 515)//516
#define OBJ_EVENT_GFX_POKEMON_517		(NUM_REGULAR_OBJ_EVENT_GFX + 516)//517
#define OBJ_EVENT_GFX_POKEMON_518		(NUM_REGULAR_OBJ_EVENT_GFX + 517)//518
#define OBJ_EVENT_GFX_POKEMON_519		(NUM_REGULAR_OBJ_EVENT_GFX + 518)//519
#define OBJ_EVENT_GFX_POKEMON_520		(NUM_REGULAR_OBJ_EVENT_GFX + 519)//520
#define OBJ_EVENT_GFX_POKEMON_521		(NUM_REGULAR_OBJ_EVENT_GFX + 520)//521
#define OBJ_EVENT_GFX_POKEMON_522		(NUM_REGULAR_OBJ_EVENT_GFX + 521)//522
#define OBJ_EVENT_GFX_POKEMON_523		(NUM_REGULAR_OBJ_EVENT_GFX + 522)//523
#define OBJ_EVENT_GFX_POKEMON_524		(NUM_REGULAR_OBJ_EVENT_GFX + 523)//525
#define OBJ_EVENT_GFX_POKEMON_525		(NUM_REGULAR_OBJ_EVENT_GFX + 524)//526
#define OBJ_EVENT_GFX_POKEMON_526		(NUM_REGULAR_OBJ_EVENT_GFX + 525)//527
#define OBJ_EVENT_GFX_POKEMON_527		(NUM_REGULAR_OBJ_EVENT_GFX + 526)//528
#define OBJ_EVENT_GFX_POKEMON_528		(NUM_REGULAR_OBJ_EVENT_GFX + 527)//529
#define OBJ_EVENT_GFX_POKEMON_529		(NUM_REGULAR_OBJ_EVENT_GFX + 528)//520
#define OBJ_EVENT_GFX_POKEMON_530		(NUM_REGULAR_OBJ_EVENT_GFX + 529)//530
#define OBJ_EVENT_GFX_POKEMON_531		(NUM_REGULAR_OBJ_EVENT_GFX + 530)//531
#define OBJ_EVENT_GFX_POKEMON_532		(NUM_REGULAR_OBJ_EVENT_GFX + 531)//532
#define OBJ_EVENT_GFX_POKEMON_533		(NUM_REGULAR_OBJ_EVENT_GFX + 532)//533
#define OBJ_EVENT_GFX_POKEMON_534		(NUM_REGULAR_OBJ_EVENT_GFX + 533)//534
#define OBJ_EVENT_GFX_POKEMON_535		(NUM_REGULAR_OBJ_EVENT_GFX + 534)//535
#define OBJ_EVENT_GFX_POKEMON_536		(NUM_REGULAR_OBJ_EVENT_GFX + 535)//536
#define OBJ_EVENT_GFX_POKEMON_537		(NUM_REGULAR_OBJ_EVENT_GFX + 536)//537
#define OBJ_EVENT_GFX_POKEMON_538		(NUM_REGULAR_OBJ_EVENT_GFX + 537)//538
#define OBJ_EVENT_GFX_POKEMON_539		(NUM_REGULAR_OBJ_EVENT_GFX + 538)//539
#define OBJ_EVENT_GFX_POKEMON_540		(NUM_REGULAR_OBJ_EVENT_GFX + 539)//540
#define OBJ_EVENT_GFX_POKEMON_541		(NUM_REGULAR_OBJ_EVENT_GFX + 540)//541
#define OBJ_EVENT_GFX_POKEMON_542		(NUM_REGULAR_OBJ_EVENT_GFX + 541)//542
#define OBJ_EVENT_GFX_POKEMON_543		(NUM_REGULAR_OBJ_EVENT_GFX + 542)//543
#define OBJ_EVENT_GFX_POKEMON_544		(NUM_REGULAR_OBJ_EVENT_GFX + 543)//544
#define OBJ_EVENT_GFX_POKEMON_545		(NUM_REGULAR_OBJ_EVENT_GFX + 544)//545
#define OBJ_EVENT_GFX_POKEMON_546		(NUM_REGULAR_OBJ_EVENT_GFX + 545)//546
#define OBJ_EVENT_GFX_POKEMON_547		(NUM_REGULAR_OBJ_EVENT_GFX + 546)//547
#define OBJ_EVENT_GFX_POKEMON_548		(NUM_REGULAR_OBJ_EVENT_GFX + 547)//548
#define OBJ_EVENT_GFX_POKEMON_549		(NUM_REGULAR_OBJ_EVENT_GFX + 548)//549
#define OBJ_EVENT_GFX_POKEMON_550		(NUM_REGULAR_OBJ_EVENT_GFX + 549)//550
#define OBJ_EVENT_GFX_POKEMON_551		(NUM_REGULAR_OBJ_EVENT_GFX + 550)//551
#define OBJ_EVENT_GFX_POKEMON_552		(NUM_REGULAR_OBJ_EVENT_GFX + 551)//552
#define OBJ_EVENT_GFX_POKEMON_553		(NUM_REGULAR_OBJ_EVENT_GFX + 552)//553
#define OBJ_EVENT_GFX_POKEMON_554		(NUM_REGULAR_OBJ_EVENT_GFX + 553)//554
#define OBJ_EVENT_GFX_POKEMON_555		(NUM_REGULAR_OBJ_EVENT_GFX + 554)//555
#define OBJ_EVENT_GFX_POKEMON_556		(NUM_REGULAR_OBJ_EVENT_GFX + 555)//556
#define OBJ_EVENT_GFX_POKEMON_557		(NUM_REGULAR_OBJ_EVENT_GFX + 556)//557
#define OBJ_EVENT_GFX_POKEMON_558		(NUM_REGULAR_OBJ_EVENT_GFX + 557)//558
#define OBJ_EVENT_GFX_POKEMON_559		(NUM_REGULAR_OBJ_EVENT_GFX + 558)//559
#define OBJ_EVENT_GFX_POKEMON_560		(NUM_REGULAR_OBJ_EVENT_GFX + 559)//560
#define OBJ_EVENT_GFX_POKEMON_561		(NUM_REGULAR_OBJ_EVENT_GFX + 560)//561
#define OBJ_EVENT_GFX_POKEMON_562		(NUM_REGULAR_OBJ_EVENT_GFX + 561)//562
#define OBJ_EVENT_GFX_POKEMON_563		(NUM_REGULAR_OBJ_EVENT_GFX + 562)//563
#define OBJ_EVENT_GFX_POKEMON_564		(NUM_REGULAR_OBJ_EVENT_GFX + 563)//564
#define OBJ_EVENT_GFX_POKEMON_565		(NUM_REGULAR_OBJ_EVENT_GFX + 564)//565
#define OBJ_EVENT_GFX_POKEMON_566		(NUM_REGULAR_OBJ_EVENT_GFX + 565)//566
#define OBJ_EVENT_GFX_POKEMON_567		(NUM_REGULAR_OBJ_EVENT_GFX + 566)//567
#define OBJ_EVENT_GFX_POKEMON_568		(NUM_REGULAR_OBJ_EVENT_GFX + 567)//568
#define OBJ_EVENT_GFX_POKEMON_569		(NUM_REGULAR_OBJ_EVENT_GFX + 568)//569
#define OBJ_EVENT_GFX_POKEMON_570		(NUM_REGULAR_OBJ_EVENT_GFX + 569)//570
#define OBJ_EVENT_GFX_POKEMON_571		(NUM_REGULAR_OBJ_EVENT_GFX + 570)//571
#define OBJ_EVENT_GFX_POKEMON_572		(NUM_REGULAR_OBJ_EVENT_GFX + 571)//572
#define OBJ_EVENT_GFX_POKEMON_573		(NUM_REGULAR_OBJ_EVENT_GFX + 572)//573
#define OBJ_EVENT_GFX_POKEMON_574		(NUM_REGULAR_OBJ_EVENT_GFX + 573)//574
#define OBJ_EVENT_GFX_POKEMON_575		(NUM_REGULAR_OBJ_EVENT_GFX + 574)//575
#define OBJ_EVENT_GFX_POKEMON_576		(NUM_REGULAR_OBJ_EVENT_GFX + 575)//576
#define OBJ_EVENT_GFX_POKEMON_577		(NUM_REGULAR_OBJ_EVENT_GFX + 576)//577
#define OBJ_EVENT_GFX_POKEMON_578		(NUM_REGULAR_OBJ_EVENT_GFX + 577)//578
#define OBJ_EVENT_GFX_POKEMON_579		(NUM_REGULAR_OBJ_EVENT_GFX + 578)//579
#define OBJ_EVENT_GFX_POKEMON_580		(NUM_REGULAR_OBJ_EVENT_GFX + 579)//580
#define OBJ_EVENT_GFX_POKEMON_581		(NUM_REGULAR_OBJ_EVENT_GFX + 580)//581
#define OBJ_EVENT_GFX_POKEMON_582		(NUM_REGULAR_OBJ_EVENT_GFX + 581)//582
#define OBJ_EVENT_GFX_POKEMON_583		(NUM_REGULAR_OBJ_EVENT_GFX + 582)//583
#define OBJ_EVENT_GFX_POKEMON_584		(NUM_REGULAR_OBJ_EVENT_GFX + 583)//584
#define OBJ_EVENT_GFX_POKEMON_585		(NUM_REGULAR_OBJ_EVENT_GFX + 584)//585
#define OBJ_EVENT_GFX_POKEMON_586		(NUM_REGULAR_OBJ_EVENT_GFX + 585)//586
#define OBJ_EVENT_GFX_POKEMON_587		(NUM_REGULAR_OBJ_EVENT_GFX + 586)//587
#define OBJ_EVENT_GFX_POKEMON_588		(NUM_REGULAR_OBJ_EVENT_GFX + 587)//588
#define OBJ_EVENT_GFX_POKEMON_589		(NUM_REGULAR_OBJ_EVENT_GFX + 588)//589
#define OBJ_EVENT_GFX_POKEMON_590		(NUM_REGULAR_OBJ_EVENT_GFX + 589)//590
#define OBJ_EVENT_GFX_POKEMON_591		(NUM_REGULAR_OBJ_EVENT_GFX + 590)//591
#define OBJ_EVENT_GFX_POKEMON_592		(NUM_REGULAR_OBJ_EVENT_GFX + 591)//592
#define OBJ_EVENT_GFX_POKEMON_593		(NUM_REGULAR_OBJ_EVENT_GFX + 592)//593
#define OBJ_EVENT_GFX_POKEMON_594		(NUM_REGULAR_OBJ_EVENT_GFX + 593)//594
#define OBJ_EVENT_GFX_POKEMON_595		(NUM_REGULAR_OBJ_EVENT_GFX + 594)//595
#define OBJ_EVENT_GFX_POKEMON_596		(NUM_REGULAR_OBJ_EVENT_GFX + 595)//596
#define OBJ_EVENT_GFX_POKEMON_597		(NUM_REGULAR_OBJ_EVENT_GFX + 596)//597
#define OBJ_EVENT_GFX_POKEMON_598		(NUM_REGULAR_OBJ_EVENT_GFX + 597)//598
#define OBJ_EVENT_GFX_POKEMON_599		(NUM_REGULAR_OBJ_EVENT_GFX + 598)//599
#define OBJ_EVENT_GFX_POKEMON_600		(NUM_REGULAR_OBJ_EVENT_GFX + 599)//600
#define OBJ_EVENT_GFX_POKEMON_601		(NUM_REGULAR_OBJ_EVENT_GFX + 600)//601
#define OBJ_EVENT_GFX_POKEMON_602		(NUM_REGULAR_OBJ_EVENT_GFX + 601)//602
#define OBJ_EVENT_GFX_POKEMON_603		(NUM_REGULAR_OBJ_EVENT_GFX + 602)//603
#define OBJ_EVENT_GFX_POKEMON_604		(NUM_REGULAR_OBJ_EVENT_GFX + 603)//604
#define OBJ_EVENT_GFX_POKEMON_605		(NUM_REGULAR_OBJ_EVENT_GFX + 604)//605
#define OBJ_EVENT_GFX_POKEMON_606		(NUM_REGULAR_OBJ_EVENT_GFX + 605)//606
#define OBJ_EVENT_GFX_POKEMON_607		(NUM_REGULAR_OBJ_EVENT_GFX + 606)//607
#define OBJ_EVENT_GFX_POKEMON_608		(NUM_REGULAR_OBJ_EVENT_GFX + 607)//608
#define OBJ_EVENT_GFX_POKEMON_609		(NUM_REGULAR_OBJ_EVENT_GFX + 608)//609
#define OBJ_EVENT_GFX_POKEMON_610		(NUM_REGULAR_OBJ_EVENT_GFX + 609)//610
#define OBJ_EVENT_GFX_POKEMON_611		(NUM_REGULAR_OBJ_EVENT_GFX + 610)//611
#define OBJ_EVENT_GFX_POKEMON_612		(NUM_REGULAR_OBJ_EVENT_GFX + 611)//612
#define OBJ_EVENT_GFX_POKEMON_613		(NUM_REGULAR_OBJ_EVENT_GFX + 612)//613
#define OBJ_EVENT_GFX_POKEMON_614		(NUM_REGULAR_OBJ_EVENT_GFX + 613)//614
#define OBJ_EVENT_GFX_POKEMON_615		(NUM_REGULAR_OBJ_EVENT_GFX + 614)//615
#define OBJ_EVENT_GFX_POKEMON_616		(NUM_REGULAR_OBJ_EVENT_GFX + 615)//616
#define OBJ_EVENT_GFX_POKEMON_617		(NUM_REGULAR_OBJ_EVENT_GFX + 616)//617
#define OBJ_EVENT_GFX_POKEMON_618		(NUM_REGULAR_OBJ_EVENT_GFX + 617)//618
#define OBJ_EVENT_GFX_POKEMON_619		(NUM_REGULAR_OBJ_EVENT_GFX + 618)//619
#define OBJ_EVENT_GFX_POKEMON_620		(NUM_REGULAR_OBJ_EVENT_GFX + 619)//620
#define OBJ_EVENT_GFX_POKEMON_621		(NUM_REGULAR_OBJ_EVENT_GFX + 620)//621
#define OBJ_EVENT_GFX_POKEMON_622		(NUM_REGULAR_OBJ_EVENT_GFX + 621)//622
#define OBJ_EVENT_GFX_POKEMON_623		(NUM_REGULAR_OBJ_EVENT_GFX + 622)//623
#define OBJ_EVENT_GFX_POKEMON_624		(NUM_REGULAR_OBJ_EVENT_GFX + 623)//624
#define OBJ_EVENT_GFX_POKEMON_625		(NUM_REGULAR_OBJ_EVENT_GFX + 624)//625
#define OBJ_EVENT_GFX_POKEMON_626		(NUM_REGULAR_OBJ_EVENT_GFX + 625)//626
#define OBJ_EVENT_GFX_POKEMON_627		(NUM_REGULAR_OBJ_EVENT_GFX + 626)//627
#define OBJ_EVENT_GFX_POKEMON_628		(NUM_REGULAR_OBJ_EVENT_GFX + 627)//628
#define OBJ_EVENT_GFX_POKEMON_629		(NUM_REGULAR_OBJ_EVENT_GFX + 628)//629
#define OBJ_EVENT_GFX_POKEMON_630		(NUM_REGULAR_OBJ_EVENT_GFX + 629)//630
#define OBJ_EVENT_GFX_POKEMON_631		(NUM_REGULAR_OBJ_EVENT_GFX + 630)//631
#define OBJ_EVENT_GFX_POKEMON_632		(NUM_REGULAR_OBJ_EVENT_GFX + 631)//632
#define OBJ_EVENT_GFX_POKEMON_633		(NUM_REGULAR_OBJ_EVENT_GFX + 632)//633
#define OBJ_EVENT_GFX_POKEMON_634		(NUM_REGULAR_OBJ_EVENT_GFX + 633)//634
#define OBJ_EVENT_GFX_POKEMON_635		(NUM_REGULAR_OBJ_EVENT_GFX + 634)//635
#define OBJ_EVENT_GFX_POKEMON_636		(NUM_REGULAR_OBJ_EVENT_GFX + 635)//636
#define OBJ_EVENT_GFX_POKEMON_637		(NUM_REGULAR_OBJ_EVENT_GFX + 636)//637
#define OBJ_EVENT_GFX_POKEMON_638		(NUM_REGULAR_OBJ_EVENT_GFX + 637)//638
#define OBJ_EVENT_GFX_POKEMON_639		(NUM_REGULAR_OBJ_EVENT_GFX + 638)//639
#define OBJ_EVENT_GFX_POKEMON_640		(NUM_REGULAR_OBJ_EVENT_GFX + 639)//640
#define OBJ_EVENT_GFX_POKEMON_641		(NUM_REGULAR_OBJ_EVENT_GFX + 640)//641
#define OBJ_EVENT_GFX_POKEMON_642		(NUM_REGULAR_OBJ_EVENT_GFX + 641)//642
#define OBJ_EVENT_GFX_POKEMON_643		(NUM_REGULAR_OBJ_EVENT_GFX + 642)//643
#define OBJ_EVENT_GFX_POKEMON_644		(NUM_REGULAR_OBJ_EVENT_GFX + 643)//644
#define OBJ_EVENT_GFX_POKEMON_645		(NUM_REGULAR_OBJ_EVENT_GFX + 644)//645
#define OBJ_EVENT_GFX_POKEMON_646		(NUM_REGULAR_OBJ_EVENT_GFX + 645)//646
#define OBJ_EVENT_GFX_POKEMON_647		(NUM_REGULAR_OBJ_EVENT_GFX + 646)//647
#define OBJ_EVENT_GFX_POKEMON_648		(NUM_REGULAR_OBJ_EVENT_GFX + 647)//648
#define OBJ_EVENT_GFX_POKEMON_649		(NUM_REGULAR_OBJ_EVENT_GFX + 648)//649

//Gen 6 (72
#define OBJ_EVENT_GFX_POKEMON_650		(NUM_REGULAR_OBJ_EVENT_GFX + 649)//650
#define OBJ_EVENT_GFX_POKEMON_651		(NUM_REGULAR_OBJ_EVENT_GFX + 650)//651
#define OBJ_EVENT_GFX_POKEMON_652		(NUM_REGULAR_OBJ_EVENT_GFX + 651)//652
#define OBJ_EVENT_GFX_POKEMON_653		(NUM_REGULAR_OBJ_EVENT_GFX + 652)//653
#define OBJ_EVENT_GFX_POKEMON_654		(NUM_REGULAR_OBJ_EVENT_GFX + 653)//654
#define OBJ_EVENT_GFX_POKEMON_655		(NUM_REGULAR_OBJ_EVENT_GFX + 654)//655
#define OBJ_EVENT_GFX_POKEMON_656		(NUM_REGULAR_OBJ_EVENT_GFX + 655)//656
#define OBJ_EVENT_GFX_POKEMON_657		(NUM_REGULAR_OBJ_EVENT_GFX + 656)//657
#define OBJ_EVENT_GFX_POKEMON_658		(NUM_REGULAR_OBJ_EVENT_GFX + 657)//658
#define OBJ_EVENT_GFX_POKEMON_659		(NUM_REGULAR_OBJ_EVENT_GFX + 658)//659
#define OBJ_EVENT_GFX_POKEMON_660		(NUM_REGULAR_OBJ_EVENT_GFX + 659)//660
#define OBJ_EVENT_GFX_POKEMON_661		(NUM_REGULAR_OBJ_EVENT_GFX + 660)//661
#define OBJ_EVENT_GFX_POKEMON_662		(NUM_REGULAR_OBJ_EVENT_GFX + 661)//662
#define OBJ_EVENT_GFX_POKEMON_663		(NUM_REGULAR_OBJ_EVENT_GFX + 662)//663
#define OBJ_EVENT_GFX_POKEMON_664		(NUM_REGULAR_OBJ_EVENT_GFX + 663)//664
#define OBJ_EVENT_GFX_POKEMON_665		(NUM_REGULAR_OBJ_EVENT_GFX + 664)//665
#define OBJ_EVENT_GFX_POKEMON_666		(NUM_REGULAR_OBJ_EVENT_GFX + 665)//666
#define OBJ_EVENT_GFX_POKEMON_667		(NUM_REGULAR_OBJ_EVENT_GFX + 666)//667
#define OBJ_EVENT_GFX_POKEMON_668		(NUM_REGULAR_OBJ_EVENT_GFX + 667)//668
#define OBJ_EVENT_GFX_POKEMON_669		(NUM_REGULAR_OBJ_EVENT_GFX + 668)//669
#define OBJ_EVENT_GFX_POKEMON_670		(NUM_REGULAR_OBJ_EVENT_GFX + 669)//670
#define OBJ_EVENT_GFX_POKEMON_671		(NUM_REGULAR_OBJ_EVENT_GFX + 670)//671
#define OBJ_EVENT_GFX_POKEMON_672		(NUM_REGULAR_OBJ_EVENT_GFX + 671)//672
#define OBJ_EVENT_GFX_POKEMON_673		(NUM_REGULAR_OBJ_EVENT_GFX + 672)//673
#define OBJ_EVENT_GFX_POKEMON_674		(NUM_REGULAR_OBJ_EVENT_GFX + 673)//674
#define OBJ_EVENT_GFX_POKEMON_675		(NUM_REGULAR_OBJ_EVENT_GFX + 674)//675
#define OBJ_EVENT_GFX_POKEMON_676		(NUM_REGULAR_OBJ_EVENT_GFX + 675)//676
#define OBJ_EVENT_GFX_POKEMON_677		(NUM_REGULAR_OBJ_EVENT_GFX + 676)//677
#define OBJ_EVENT_GFX_POKEMON_678		(NUM_REGULAR_OBJ_EVENT_GFX + 677)//678
#define OBJ_EVENT_GFX_POKEMON_679		(NUM_REGULAR_OBJ_EVENT_GFX + 678)//679
#define OBJ_EVENT_GFX_POKEMON_680		(NUM_REGULAR_OBJ_EVENT_GFX + 679)//680
#define OBJ_EVENT_GFX_POKEMON_681		(NUM_REGULAR_OBJ_EVENT_GFX + 680)//681
#define OBJ_EVENT_GFX_POKEMON_682		(NUM_REGULAR_OBJ_EVENT_GFX + 681)//682
#define OBJ_EVENT_GFX_POKEMON_683		(NUM_REGULAR_OBJ_EVENT_GFX + 682)//683
#define OBJ_EVENT_GFX_POKEMON_684		(NUM_REGULAR_OBJ_EVENT_GFX + 683)//684
#define OBJ_EVENT_GFX_POKEMON_685		(NUM_REGULAR_OBJ_EVENT_GFX + 684)//685
#define OBJ_EVENT_GFX_POKEMON_686		(NUM_REGULAR_OBJ_EVENT_GFX + 685)//686
#define OBJ_EVENT_GFX_POKEMON_687		(NUM_REGULAR_OBJ_EVENT_GFX + 686)//687
#define OBJ_EVENT_GFX_POKEMON_688		(NUM_REGULAR_OBJ_EVENT_GFX + 687)//688
#define OBJ_EVENT_GFX_POKEMON_689		(NUM_REGULAR_OBJ_EVENT_GFX + 688)//689
#define OBJ_EVENT_GFX_POKEMON_690		(NUM_REGULAR_OBJ_EVENT_GFX + 689)//690
#define OBJ_EVENT_GFX_POKEMON_691		(NUM_REGULAR_OBJ_EVENT_GFX + 690)//691
#define OBJ_EVENT_GFX_POKEMON_692		(NUM_REGULAR_OBJ_EVENT_GFX + 691)//692
#define OBJ_EVENT_GFX_POKEMON_693		(NUM_REGULAR_OBJ_EVENT_GFX + 692)//693
#define OBJ_EVENT_GFX_POKEMON_694		(NUM_REGULAR_OBJ_EVENT_GFX + 693)//694
#define OBJ_EVENT_GFX_POKEMON_695		(NUM_REGULAR_OBJ_EVENT_GFX + 694)//695
#define OBJ_EVENT_GFX_POKEMON_696		(NUM_REGULAR_OBJ_EVENT_GFX + 695)//696
#define OBJ_EVENT_GFX_POKEMON_697		(NUM_REGULAR_OBJ_EVENT_GFX + 696)//697
#define OBJ_EVENT_GFX_POKEMON_698		(NUM_REGULAR_OBJ_EVENT_GFX + 697)//698
#define OBJ_EVENT_GFX_POKEMON_699		(NUM_REGULAR_OBJ_EVENT_GFX + 698)//699
#define OBJ_EVENT_GFX_POKEMON_700		(NUM_REGULAR_OBJ_EVENT_GFX + 699)//700
#define OBJ_EVENT_GFX_POKEMON_701		(NUM_REGULAR_OBJ_EVENT_GFX + 700)//701
#define OBJ_EVENT_GFX_POKEMON_702		(NUM_REGULAR_OBJ_EVENT_GFX + 701)//702
#define OBJ_EVENT_GFX_POKEMON_703		(NUM_REGULAR_OBJ_EVENT_GFX + 702)//703
#define OBJ_EVENT_GFX_POKEMON_704		(NUM_REGULAR_OBJ_EVENT_GFX + 703)//704
#define OBJ_EVENT_GFX_POKEMON_705		(NUM_REGULAR_OBJ_EVENT_GFX + 704)//705
#define OBJ_EVENT_GFX_POKEMON_706		(NUM_REGULAR_OBJ_EVENT_GFX + 705)//706
#define OBJ_EVENT_GFX_POKEMON_707		(NUM_REGULAR_OBJ_EVENT_GFX + 706)//707
#define OBJ_EVENT_GFX_POKEMON_708		(NUM_REGULAR_OBJ_EVENT_GFX + 707)//708
#define OBJ_EVENT_GFX_POKEMON_709		(NUM_REGULAR_OBJ_EVENT_GFX + 708)//709
#define OBJ_EVENT_GFX_POKEMON_710		(NUM_REGULAR_OBJ_EVENT_GFX + 709)//710
#define OBJ_EVENT_GFX_POKEMON_711		(NUM_REGULAR_OBJ_EVENT_GFX + 710)//711
#define OBJ_EVENT_GFX_POKEMON_712		(NUM_REGULAR_OBJ_EVENT_GFX + 711)//712
#define OBJ_EVENT_GFX_POKEMON_713		(NUM_REGULAR_OBJ_EVENT_GFX + 712)//713
#define OBJ_EVENT_GFX_POKEMON_714		(NUM_REGULAR_OBJ_EVENT_GFX + 713)//714
#define OBJ_EVENT_GFX_POKEMON_715		(NUM_REGULAR_OBJ_EVENT_GFX + 714)//715
#define OBJ_EVENT_GFX_POKEMON_716		(NUM_REGULAR_OBJ_EVENT_GFX + 715)//716
#define OBJ_EVENT_GFX_POKEMON_717		(NUM_REGULAR_OBJ_EVENT_GFX + 716)//717
#define OBJ_EVENT_GFX_POKEMON_718		(NUM_REGULAR_OBJ_EVENT_GFX + 717)//718
#define OBJ_EVENT_GFX_POKEMON_719		(NUM_REGULAR_OBJ_EVENT_GFX + 718)//719
#define OBJ_EVENT_GFX_POKEMON_720		(NUM_REGULAR_OBJ_EVENT_GFX + 719)//720
#define OBJ_EVENT_GFX_POKEMON_721		(NUM_REGULAR_OBJ_EVENT_GFX + 720)//721

//Gen 7 (88
#define OBJ_EVENT_GFX_POKEMON_722		(NUM_REGULAR_OBJ_EVENT_GFX + 721)//722
#define OBJ_EVENT_GFX_POKEMON_723		(NUM_REGULAR_OBJ_EVENT_GFX + 722)//723
#define OBJ_EVENT_GFX_POKEMON_724		(NUM_REGULAR_OBJ_EVENT_GFX + 723)//724
#define OBJ_EVENT_GFX_POKEMON_725		(NUM_REGULAR_OBJ_EVENT_GFX + 724)//725
#define OBJ_EVENT_GFX_POKEMON_726		(NUM_REGULAR_OBJ_EVENT_GFX + 725)//726
#define OBJ_EVENT_GFX_POKEMON_727		(NUM_REGULAR_OBJ_EVENT_GFX + 726)//727
#define OBJ_EVENT_GFX_POKEMON_728		(NUM_REGULAR_OBJ_EVENT_GFX + 727)//728
#define OBJ_EVENT_GFX_POKEMON_729		(NUM_REGULAR_OBJ_EVENT_GFX + 728)//729
#define OBJ_EVENT_GFX_POKEMON_730		(NUM_REGULAR_OBJ_EVENT_GFX + 729)//730
#define OBJ_EVENT_GFX_POKEMON_731		(NUM_REGULAR_OBJ_EVENT_GFX + 730)//731
#define OBJ_EVENT_GFX_POKEMON_732		(NUM_REGULAR_OBJ_EVENT_GFX + 731)//732
#define OBJ_EVENT_GFX_POKEMON_733		(NUM_REGULAR_OBJ_EVENT_GFX + 732)//733
#define OBJ_EVENT_GFX_POKEMON_734		(NUM_REGULAR_OBJ_EVENT_GFX + 733)//734
#define OBJ_EVENT_GFX_POKEMON_735		(NUM_REGULAR_OBJ_EVENT_GFX + 734)//735
#define OBJ_EVENT_GFX_POKEMON_736		(NUM_REGULAR_OBJ_EVENT_GFX + 735)//736
#define OBJ_EVENT_GFX_POKEMON_737		(NUM_REGULAR_OBJ_EVENT_GFX + 736)//737
#define OBJ_EVENT_GFX_POKEMON_738		(NUM_REGULAR_OBJ_EVENT_GFX + 737)//738
#define OBJ_EVENT_GFX_POKEMON_739		(NUM_REGULAR_OBJ_EVENT_GFX + 738)//739
#define OBJ_EVENT_GFX_POKEMON_740		(NUM_REGULAR_OBJ_EVENT_GFX + 739)//740
#define OBJ_EVENT_GFX_POKEMON_741		(NUM_REGULAR_OBJ_EVENT_GFX + 740)//741
#define OBJ_EVENT_GFX_POKEMON_742		(NUM_REGULAR_OBJ_EVENT_GFX + 741)//742
#define OBJ_EVENT_GFX_POKEMON_743		(NUM_REGULAR_OBJ_EVENT_GFX + 742)//743
#define OBJ_EVENT_GFX_POKEMON_744		(NUM_REGULAR_OBJ_EVENT_GFX + 743)//744
#define OBJ_EVENT_GFX_POKEMON_745		(NUM_REGULAR_OBJ_EVENT_GFX + 744)//745
#define OBJ_EVENT_GFX_POKEMON_746		(NUM_REGULAR_OBJ_EVENT_GFX + 745)//746
#define OBJ_EVENT_GFX_POKEMON_747		(NUM_REGULAR_OBJ_EVENT_GFX + 746)//747
#define OBJ_EVENT_GFX_POKEMON_748		(NUM_REGULAR_OBJ_EVENT_GFX + 747)//748
#define OBJ_EVENT_GFX_POKEMON_749		(NUM_REGULAR_OBJ_EVENT_GFX + 748)//749
#define OBJ_EVENT_GFX_POKEMON_750		(NUM_REGULAR_OBJ_EVENT_GFX + 749)//750
#define OBJ_EVENT_GFX_POKEMON_751		(NUM_REGULAR_OBJ_EVENT_GFX + 750)//751
#define OBJ_EVENT_GFX_POKEMON_752		(NUM_REGULAR_OBJ_EVENT_GFX + 751)//752
#define OBJ_EVENT_GFX_POKEMON_753		(NUM_REGULAR_OBJ_EVENT_GFX + 752)//753
#define OBJ_EVENT_GFX_POKEMON_754		(NUM_REGULAR_OBJ_EVENT_GFX + 753)//754
#define OBJ_EVENT_GFX_POKEMON_755		(NUM_REGULAR_OBJ_EVENT_GFX + 754)//755
#define OBJ_EVENT_GFX_POKEMON_756		(NUM_REGULAR_OBJ_EVENT_GFX + 755)//756
#define OBJ_EVENT_GFX_POKEMON_757		(NUM_REGULAR_OBJ_EVENT_GFX + 756)//757
#define OBJ_EVENT_GFX_POKEMON_758		(NUM_REGULAR_OBJ_EVENT_GFX + 757)//758
#define OBJ_EVENT_GFX_POKEMON_759		(NUM_REGULAR_OBJ_EVENT_GFX + 758)//759
#define OBJ_EVENT_GFX_POKEMON_760		(NUM_REGULAR_OBJ_EVENT_GFX + 759)//760
#define OBJ_EVENT_GFX_POKEMON_761		(NUM_REGULAR_OBJ_EVENT_GFX + 760)//761
#define OBJ_EVENT_GFX_POKEMON_762		(NUM_REGULAR_OBJ_EVENT_GFX + 761)//762
#define OBJ_EVENT_GFX_POKEMON_763		(NUM_REGULAR_OBJ_EVENT_GFX + 762)//763
#define OBJ_EVENT_GFX_POKEMON_764		(NUM_REGULAR_OBJ_EVENT_GFX + 763)//764
#define OBJ_EVENT_GFX_POKEMON_765		(NUM_REGULAR_OBJ_EVENT_GFX + 764)//765
#define OBJ_EVENT_GFX_POKEMON_766		(NUM_REGULAR_OBJ_EVENT_GFX + 765)//766
#define OBJ_EVENT_GFX_POKEMON_767		(NUM_REGULAR_OBJ_EVENT_GFX + 766)//767
#define OBJ_EVENT_GFX_POKEMON_768		(NUM_REGULAR_OBJ_EVENT_GFX + 767)//768
#define OBJ_EVENT_GFX_POKEMON_769		(NUM_REGULAR_OBJ_EVENT_GFX + 768)//769
#define OBJ_EVENT_GFX_POKEMON_770		(NUM_REGULAR_OBJ_EVENT_GFX + 769)//770
#define OBJ_EVENT_GFX_POKEMON_771		(NUM_REGULAR_OBJ_EVENT_GFX + 770)//771
#define OBJ_EVENT_GFX_POKEMON_772		(NUM_REGULAR_OBJ_EVENT_GFX + 771)//772
#define OBJ_EVENT_GFX_POKEMON_773		(NUM_REGULAR_OBJ_EVENT_GFX + 772)//773
#define OBJ_EVENT_GFX_POKEMON_774		(NUM_REGULAR_OBJ_EVENT_GFX + 773)//774
#define OBJ_EVENT_GFX_POKEMON_775		(NUM_REGULAR_OBJ_EVENT_GFX + 774)//775
#define OBJ_EVENT_GFX_POKEMON_776		(NUM_REGULAR_OBJ_EVENT_GFX + 775)//776
#define OBJ_EVENT_GFX_POKEMON_777		(NUM_REGULAR_OBJ_EVENT_GFX + 776)//777
#define OBJ_EVENT_GFX_POKEMON_778		(NUM_REGULAR_OBJ_EVENT_GFX + 777)//778
#define OBJ_EVENT_GFX_POKEMON_779		(NUM_REGULAR_OBJ_EVENT_GFX + 778)//779
#define OBJ_EVENT_GFX_POKEMON_780		(NUM_REGULAR_OBJ_EVENT_GFX + 779)//780
#define OBJ_EVENT_GFX_POKEMON_781		(NUM_REGULAR_OBJ_EVENT_GFX + 780)//781
#define OBJ_EVENT_GFX_POKEMON_782		(NUM_REGULAR_OBJ_EVENT_GFX + 781)//782
#define OBJ_EVENT_GFX_POKEMON_783		(NUM_REGULAR_OBJ_EVENT_GFX + 782)//783
#define OBJ_EVENT_GFX_POKEMON_784		(NUM_REGULAR_OBJ_EVENT_GFX + 783)//784
#define OBJ_EVENT_GFX_POKEMON_785		(NUM_REGULAR_OBJ_EVENT_GFX + 784)//785
#define OBJ_EVENT_GFX_POKEMON_786		(NUM_REGULAR_OBJ_EVENT_GFX + 785)//786
#define OBJ_EVENT_GFX_POKEMON_787		(NUM_REGULAR_OBJ_EVENT_GFX + 786)//787
#define OBJ_EVENT_GFX_POKEMON_788		(NUM_REGULAR_OBJ_EVENT_GFX + 787)//788
#define OBJ_EVENT_GFX_POKEMON_789		(NUM_REGULAR_OBJ_EVENT_GFX + 788)//789
#define OBJ_EVENT_GFX_POKEMON_790		(NUM_REGULAR_OBJ_EVENT_GFX + 789)//790
#define OBJ_EVENT_GFX_POKEMON_791		(NUM_REGULAR_OBJ_EVENT_GFX + 790)//791
#define OBJ_EVENT_GFX_POKEMON_792		(NUM_REGULAR_OBJ_EVENT_GFX + 791)//792
#define OBJ_EVENT_GFX_POKEMON_793		(NUM_REGULAR_OBJ_EVENT_GFX + 792)//793
#define OBJ_EVENT_GFX_POKEMON_794		(NUM_REGULAR_OBJ_EVENT_GFX + 793)//794
#define OBJ_EVENT_GFX_POKEMON_795		(NUM_REGULAR_OBJ_EVENT_GFX + 794)//795
#define OBJ_EVENT_GFX_POKEMON_796		(NUM_REGULAR_OBJ_EVENT_GFX + 795)//796
#define OBJ_EVENT_GFX_POKEMON_797		(NUM_REGULAR_OBJ_EVENT_GFX + 796)//797
#define OBJ_EVENT_GFX_POKEMON_798		(NUM_REGULAR_OBJ_EVENT_GFX + 797)//798
#define OBJ_EVENT_GFX_POKEMON_799		(NUM_REGULAR_OBJ_EVENT_GFX + 798)//799
#define OBJ_EVENT_GFX_POKEMON_800		(NUM_REGULAR_OBJ_EVENT_GFX + 799)//800
#define OBJ_EVENT_GFX_POKEMON_801		(NUM_REGULAR_OBJ_EVENT_GFX + 800)//801
#define OBJ_EVENT_GFX_POKEMON_802		(NUM_REGULAR_OBJ_EVENT_GFX + 801)//802
#define OBJ_EVENT_GFX_POKEMON_803		(NUM_REGULAR_OBJ_EVENT_GFX + 802)//803
#define OBJ_EVENT_GFX_POKEMON_804		(NUM_REGULAR_OBJ_EVENT_GFX + 803)//804
#define OBJ_EVENT_GFX_POKEMON_805		(NUM_REGULAR_OBJ_EVENT_GFX + 804)//805
#define OBJ_EVENT_GFX_POKEMON_806		(NUM_REGULAR_OBJ_EVENT_GFX + 805)//806
#define OBJ_EVENT_GFX_POKEMON_807		(NUM_REGULAR_OBJ_EVENT_GFX + 806)//807
#define OBJ_EVENT_GFX_POKEMON_808		(NUM_REGULAR_OBJ_EVENT_GFX + 807)//808
#define OBJ_EVENT_GFX_POKEMON_809		(NUM_REGULAR_OBJ_EVENT_GFX + 808)//809

// Gen 8 (96
#define OBJ_EVENT_GFX_POKEMON_810       (NUM_REGULAR_OBJ_EVENT_GFX + 809)//810
#define OBJ_EVENT_GFX_POKEMON_811       (NUM_REGULAR_OBJ_EVENT_GFX + 810)//811
#define OBJ_EVENT_GFX_POKEMON_812       (NUM_REGULAR_OBJ_EVENT_GFX + 811)//812
#define OBJ_EVENT_GFX_POKEMON_813       (NUM_REGULAR_OBJ_EVENT_GFX + 812)//813
#define OBJ_EVENT_GFX_POKEMON_814       (NUM_REGULAR_OBJ_EVENT_GFX + 813)//814
#define OBJ_EVENT_GFX_POKEMON_815       (NUM_REGULAR_OBJ_EVENT_GFX + 814)//815
#define OBJ_EVENT_GFX_POKEMON_816       (NUM_REGULAR_OBJ_EVENT_GFX + 815)//816
#define OBJ_EVENT_GFX_POKEMON_817       (NUM_REGULAR_OBJ_EVENT_GFX + 816)//817
#define OBJ_EVENT_GFX_POKEMON_818       (NUM_REGULAR_OBJ_EVENT_GFX + 817)//818
#define OBJ_EVENT_GFX_POKEMON_819       (NUM_REGULAR_OBJ_EVENT_GFX + 818)//819
#define OBJ_EVENT_GFX_POKEMON_820       (NUM_REGULAR_OBJ_EVENT_GFX + 819)//820
#define OBJ_EVENT_GFX_POKEMON_821       (NUM_REGULAR_OBJ_EVENT_GFX + 820)//821
#define OBJ_EVENT_GFX_POKEMON_822       (NUM_REGULAR_OBJ_EVENT_GFX + 821)//822
#define OBJ_EVENT_GFX_POKEMON_823       (NUM_REGULAR_OBJ_EVENT_GFX + 822)//823
#define OBJ_EVENT_GFX_POKEMON_824       (NUM_REGULAR_OBJ_EVENT_GFX + 823)//824
#define OBJ_EVENT_GFX_POKEMON_825       (NUM_REGULAR_OBJ_EVENT_GFX + 824)//825
#define OBJ_EVENT_GFX_POKEMON_826       (NUM_REGULAR_OBJ_EVENT_GFX + 825)//826
#define OBJ_EVENT_GFX_POKEMON_827       (NUM_REGULAR_OBJ_EVENT_GFX + 826)//827
#define OBJ_EVENT_GFX_POKEMON_828       (NUM_REGULAR_OBJ_EVENT_GFX + 827)//828
#define OBJ_EVENT_GFX_POKEMON_829       (NUM_REGULAR_OBJ_EVENT_GFX + 828)//829
#define OBJ_EVENT_GFX_POKEMON_830       (NUM_REGULAR_OBJ_EVENT_GFX + 829)//830
#define OBJ_EVENT_GFX_POKEMON_831       (NUM_REGULAR_OBJ_EVENT_GFX + 830)//831
#define OBJ_EVENT_GFX_POKEMON_832       (NUM_REGULAR_OBJ_EVENT_GFX + 831)//832
#define OBJ_EVENT_GFX_POKEMON_833       (NUM_REGULAR_OBJ_EVENT_GFX + 832)//833
#define OBJ_EVENT_GFX_POKEMON_834       (NUM_REGULAR_OBJ_EVENT_GFX + 833)//834
#define OBJ_EVENT_GFX_POKEMON_835       (NUM_REGULAR_OBJ_EVENT_GFX + 834)//835
#define OBJ_EVENT_GFX_POKEMON_836       (NUM_REGULAR_OBJ_EVENT_GFX + 835)//836
#define OBJ_EVENT_GFX_POKEMON_837       (NUM_REGULAR_OBJ_EVENT_GFX + 836)//837
#define OBJ_EVENT_GFX_POKEMON_838       (NUM_REGULAR_OBJ_EVENT_GFX + 837)//838
#define OBJ_EVENT_GFX_POKEMON_839       (NUM_REGULAR_OBJ_EVENT_GFX + 838)//839
#define OBJ_EVENT_GFX_POKEMON_840       (NUM_REGULAR_OBJ_EVENT_GFX + 839)//840
#define OBJ_EVENT_GFX_POKEMON_841       (NUM_REGULAR_OBJ_EVENT_GFX + 840)//841
#define OBJ_EVENT_GFX_POKEMON_842       (NUM_REGULAR_OBJ_EVENT_GFX + 841)//842
#define OBJ_EVENT_GFX_POKEMON_843       (NUM_REGULAR_OBJ_EVENT_GFX + 842)//843
#define OBJ_EVENT_GFX_POKEMON_844       (NUM_REGULAR_OBJ_EVENT_GFX + 843)//844
#define OBJ_EVENT_GFX_POKEMON_845       (NUM_REGULAR_OBJ_EVENT_GFX + 844)//845
#define OBJ_EVENT_GFX_POKEMON_846       (NUM_REGULAR_OBJ_EVENT_GFX + 845)//846
#define OBJ_EVENT_GFX_POKEMON_847       (NUM_REGULAR_OBJ_EVENT_GFX + 846)//847
#define OBJ_EVENT_GFX_POKEMON_848       (NUM_REGULAR_OBJ_EVENT_GFX + 847)//848
#define OBJ_EVENT_GFX_POKEMON_849       (NUM_REGULAR_OBJ_EVENT_GFX + 848)//849
#define OBJ_EVENT_GFX_POKEMON_850       (NUM_REGULAR_OBJ_EVENT_GFX + 849)//850
#define OBJ_EVENT_GFX_POKEMON_851       (NUM_REGULAR_OBJ_EVENT_GFX + 850)//851
#define OBJ_EVENT_GFX_POKEMON_852       (NUM_REGULAR_OBJ_EVENT_GFX + 851)//852
#define OBJ_EVENT_GFX_POKEMON_853       (NUM_REGULAR_OBJ_EVENT_GFX + 852)//853
#define OBJ_EVENT_GFX_POKEMON_854       (NUM_REGULAR_OBJ_EVENT_GFX + 853)//854
#define OBJ_EVENT_GFX_POKEMON_855       (NUM_REGULAR_OBJ_EVENT_GFX + 854)//855
#define OBJ_EVENT_GFX_POKEMON_856       (NUM_REGULAR_OBJ_EVENT_GFX + 855)//856
#define OBJ_EVENT_GFX_POKEMON_857       (NUM_REGULAR_OBJ_EVENT_GFX + 856)//857
#define OBJ_EVENT_GFX_POKEMON_858       (NUM_REGULAR_OBJ_EVENT_GFX + 857)//858
#define OBJ_EVENT_GFX_POKEMON_859       (NUM_REGULAR_OBJ_EVENT_GFX + 858)//859
#define OBJ_EVENT_GFX_POKEMON_860       (NUM_REGULAR_OBJ_EVENT_GFX + 859)//860
#define OBJ_EVENT_GFX_POKEMON_861       (NUM_REGULAR_OBJ_EVENT_GFX + 860)//861
#define OBJ_EVENT_GFX_POKEMON_862       (NUM_REGULAR_OBJ_EVENT_GFX + 861)//862
#define OBJ_EVENT_GFX_POKEMON_863       (NUM_REGULAR_OBJ_EVENT_GFX + 862)//863
#define OBJ_EVENT_GFX_POKEMON_864       (NUM_REGULAR_OBJ_EVENT_GFX + 863)//864
#define OBJ_EVENT_GFX_POKEMON_865       (NUM_REGULAR_OBJ_EVENT_GFX + 864)//865
#define OBJ_EVENT_GFX_POKEMON_866       (NUM_REGULAR_OBJ_EVENT_GFX + 865)//866
#define OBJ_EVENT_GFX_POKEMON_867       (NUM_REGULAR_OBJ_EVENT_GFX + 866)//867
#define OBJ_EVENT_GFX_POKEMON_868       (NUM_REGULAR_OBJ_EVENT_GFX + 867)//868
#define OBJ_EVENT_GFX_POKEMON_869       (NUM_REGULAR_OBJ_EVENT_GFX + 868)//869
#define OBJ_EVENT_GFX_POKEMON_870       (NUM_REGULAR_OBJ_EVENT_GFX + 869)//870
#define OBJ_EVENT_GFX_POKEMON_871       (NUM_REGULAR_OBJ_EVENT_GFX + 870)//871
#define OBJ_EVENT_GFX_POKEMON_872       (NUM_REGULAR_OBJ_EVENT_GFX + 871)//872
#define OBJ_EVENT_GFX_POKEMON_873       (NUM_REGULAR_OBJ_EVENT_GFX + 872)//873
#define OBJ_EVENT_GFX_POKEMON_874       (NUM_REGULAR_OBJ_EVENT_GFX + 873)//874
#define OBJ_EVENT_GFX_POKEMON_875       (NUM_REGULAR_OBJ_EVENT_GFX + 874)//875
#define OBJ_EVENT_GFX_POKEMON_876       (NUM_REGULAR_OBJ_EVENT_GFX + 875)//876
#define OBJ_EVENT_GFX_POKEMON_877       (NUM_REGULAR_OBJ_EVENT_GFX + 876)//877
#define OBJ_EVENT_GFX_POKEMON_878       (NUM_REGULAR_OBJ_EVENT_GFX + 877)//878
#define OBJ_EVENT_GFX_POKEMON_879       (NUM_REGULAR_OBJ_EVENT_GFX + 878)//879
#define OBJ_EVENT_GFX_POKEMON_880       (NUM_REGULAR_OBJ_EVENT_GFX + 879)//880
#define OBJ_EVENT_GFX_POKEMON_881       (NUM_REGULAR_OBJ_EVENT_GFX + 880)//881
#define OBJ_EVENT_GFX_POKEMON_882       (NUM_REGULAR_OBJ_EVENT_GFX + 881)//882
#define OBJ_EVENT_GFX_POKEMON_883       (NUM_REGULAR_OBJ_EVENT_GFX + 882)//883
#define OBJ_EVENT_GFX_POKEMON_884       (NUM_REGULAR_OBJ_EVENT_GFX + 883)//884
#define OBJ_EVENT_GFX_POKEMON_885       (NUM_REGULAR_OBJ_EVENT_GFX + 884)//885
#define OBJ_EVENT_GFX_POKEMON_886       (NUM_REGULAR_OBJ_EVENT_GFX + 885)//886
#define OBJ_EVENT_GFX_POKEMON_887       (NUM_REGULAR_OBJ_EVENT_GFX + 886)//887
#define OBJ_EVENT_GFX_POKEMON_888       (NUM_REGULAR_OBJ_EVENT_GFX + 887)//888
#define OBJ_EVENT_GFX_POKEMON_889       (NUM_REGULAR_OBJ_EVENT_GFX + 888)//889
#define OBJ_EVENT_GFX_POKEMON_890       (NUM_REGULAR_OBJ_EVENT_GFX + 889)//890
#define OBJ_EVENT_GFX_POKEMON_891       (NUM_REGULAR_OBJ_EVENT_GFX + 890)//891
#define OBJ_EVENT_GFX_POKEMON_892       (NUM_REGULAR_OBJ_EVENT_GFX + 891)//892
#define OBJ_EVENT_GFX_POKEMON_893       (NUM_REGULAR_OBJ_EVENT_GFX + 892)//893
#define OBJ_EVENT_GFX_POKEMON_894       (NUM_REGULAR_OBJ_EVENT_GFX + 893)//894
#define OBJ_EVENT_GFX_POKEMON_895       (NUM_REGULAR_OBJ_EVENT_GFX + 894)//895
#define OBJ_EVENT_GFX_POKEMON_896       (NUM_REGULAR_OBJ_EVENT_GFX + 895)//896
#define OBJ_EVENT_GFX_POKEMON_897       (NUM_REGULAR_OBJ_EVENT_GFX + 896)//897
#define OBJ_EVENT_GFX_POKEMON_898       (NUM_REGULAR_OBJ_EVENT_GFX + 897)//898
#define OBJ_EVENT_GFX_POKEMON_899       (NUM_REGULAR_OBJ_EVENT_GFX + 898)//899
#define OBJ_EVENT_GFX_POKEMON_900       (NUM_REGULAR_OBJ_EVENT_GFX + 899)//900
#define OBJ_EVENT_GFX_POKEMON_901       (NUM_REGULAR_OBJ_EVENT_GFX + 900)//901
#define OBJ_EVENT_GFX_POKEMON_902       (NUM_REGULAR_OBJ_EVENT_GFX + 901)//902
#define OBJ_EVENT_GFX_POKEMON_903       (NUM_REGULAR_OBJ_EVENT_GFX + 902)//903
#define OBJ_EVENT_GFX_POKEMON_904       (NUM_REGULAR_OBJ_EVENT_GFX + 903)//904
#define OBJ_EVENT_GFX_POKEMON_905       (NUM_REGULAR_OBJ_EVENT_GFX + 904)//905


// Gen 9 (112
#define OBJ_EVENT_GFX_POKEMON_906       (NUM_REGULAR_OBJ_EVENT_GFX + 905)//906
#define OBJ_EVENT_GFX_POKEMON_907       (NUM_REGULAR_OBJ_EVENT_GFX + 906)//907
#define OBJ_EVENT_GFX_POKEMON_908       (NUM_REGULAR_OBJ_EVENT_GFX + 907)//908
#define OBJ_EVENT_GFX_POKEMON_909       (NUM_REGULAR_OBJ_EVENT_GFX + 908)//909
#define OBJ_EVENT_GFX_POKEMON_910       (NUM_REGULAR_OBJ_EVENT_GFX + 909)//910
#define OBJ_EVENT_GFX_POKEMON_911       (NUM_REGULAR_OBJ_EVENT_GFX + 910)//911
#define OBJ_EVENT_GFX_POKEMON_912       (NUM_REGULAR_OBJ_EVENT_GFX + 911)//912
#define OBJ_EVENT_GFX_POKEMON_913       (NUM_REGULAR_OBJ_EVENT_GFX + 912)//913
#define OBJ_EVENT_GFX_POKEMON_914       (NUM_REGULAR_OBJ_EVENT_GFX + 913)//914
#define OBJ_EVENT_GFX_POKEMON_915       (NUM_REGULAR_OBJ_EVENT_GFX + 914)//915
#define OBJ_EVENT_GFX_POKEMON_916       (NUM_REGULAR_OBJ_EVENT_GFX + 915)//916
#define OBJ_EVENT_GFX_POKEMON_917       (NUM_REGULAR_OBJ_EVENT_GFX + 916)//917
#define OBJ_EVENT_GFX_POKEMON_918       (NUM_REGULAR_OBJ_EVENT_GFX + 917)//918
#define OBJ_EVENT_GFX_POKEMON_919       (NUM_REGULAR_OBJ_EVENT_GFX + 918)//919
#define OBJ_EVENT_GFX_POKEMON_920       (NUM_REGULAR_OBJ_EVENT_GFX + 919)//920
#define OBJ_EVENT_GFX_POKEMON_921       (NUM_REGULAR_OBJ_EVENT_GFX + 920)//921
#define OBJ_EVENT_GFX_POKEMON_922       (NUM_REGULAR_OBJ_EVENT_GFX + 921)//922
#define OBJ_EVENT_GFX_POKEMON_923       (NUM_REGULAR_OBJ_EVENT_GFX + 922)//923
#define OBJ_EVENT_GFX_POKEMON_924       (NUM_REGULAR_OBJ_EVENT_GFX + 923)//924
#define OBJ_EVENT_GFX_POKEMON_925       (NUM_REGULAR_OBJ_EVENT_GFX + 924)//925
#define OBJ_EVENT_GFX_POKEMON_926       (NUM_REGULAR_OBJ_EVENT_GFX + 925)//926
#define OBJ_EVENT_GFX_POKEMON_927       (NUM_REGULAR_OBJ_EVENT_GFX + 926)//927
#define OBJ_EVENT_GFX_POKEMON_928       (NUM_REGULAR_OBJ_EVENT_GFX + 927)//928
#define OBJ_EVENT_GFX_POKEMON_929       (NUM_REGULAR_OBJ_EVENT_GFX + 928)//929
#define OBJ_EVENT_GFX_POKEMON_930       (NUM_REGULAR_OBJ_EVENT_GFX + 929)//930
#define OBJ_EVENT_GFX_POKEMON_931       (NUM_REGULAR_OBJ_EVENT_GFX + 930)//931
#define OBJ_EVENT_GFX_POKEMON_932       (NUM_REGULAR_OBJ_EVENT_GFX + 931)//932
#define OBJ_EVENT_GFX_POKEMON_933       (NUM_REGULAR_OBJ_EVENT_GFX + 932)//933
#define OBJ_EVENT_GFX_POKEMON_934       (NUM_REGULAR_OBJ_EVENT_GFX + 933)//934
#define OBJ_EVENT_GFX_POKEMON_935       (NUM_REGULAR_OBJ_EVENT_GFX + 934)//935
#define OBJ_EVENT_GFX_POKEMON_936       (NUM_REGULAR_OBJ_EVENT_GFX + 935)//936
#define OBJ_EVENT_GFX_POKEMON_937       (NUM_REGULAR_OBJ_EVENT_GFX + 936)//937
#define OBJ_EVENT_GFX_POKEMON_938       (NUM_REGULAR_OBJ_EVENT_GFX + 937)//938
#define OBJ_EVENT_GFX_POKEMON_939       (NUM_REGULAR_OBJ_EVENT_GFX + 938)//939
#define OBJ_EVENT_GFX_POKEMON_940       (NUM_REGULAR_OBJ_EVENT_GFX + 939)//940
#define OBJ_EVENT_GFX_POKEMON_941       (NUM_REGULAR_OBJ_EVENT_GFX + 940)//941
#define OBJ_EVENT_GFX_POKEMON_942       (NUM_REGULAR_OBJ_EVENT_GFX + 941)//942
#define OBJ_EVENT_GFX_POKEMON_943       (NUM_REGULAR_OBJ_EVENT_GFX + 942)//943
#define OBJ_EVENT_GFX_POKEMON_944       (NUM_REGULAR_OBJ_EVENT_GFX + 943)//944
#define OBJ_EVENT_GFX_POKEMON_945       (NUM_REGULAR_OBJ_EVENT_GFX + 944)//945
#define OBJ_EVENT_GFX_POKEMON_946       (NUM_REGULAR_OBJ_EVENT_GFX + 945)//946
#define OBJ_EVENT_GFX_POKEMON_947       (NUM_REGULAR_OBJ_EVENT_GFX + 946)//947
#define OBJ_EVENT_GFX_POKEMON_948       (NUM_REGULAR_OBJ_EVENT_GFX + 947)//948
#define OBJ_EVENT_GFX_POKEMON_949       (NUM_REGULAR_OBJ_EVENT_GFX + 948)//949
#define OBJ_EVENT_GFX_POKEMON_950       (NUM_REGULAR_OBJ_EVENT_GFX + 949)//950
#define OBJ_EVENT_GFX_POKEMON_951       (NUM_REGULAR_OBJ_EVENT_GFX + 950)//951
#define OBJ_EVENT_GFX_POKEMON_952       (NUM_REGULAR_OBJ_EVENT_GFX + 951)//952
#define OBJ_EVENT_GFX_POKEMON_953       (NUM_REGULAR_OBJ_EVENT_GFX + 952)//953
#define OBJ_EVENT_GFX_POKEMON_954       (NUM_REGULAR_OBJ_EVENT_GFX + 953)//954
#define OBJ_EVENT_GFX_POKEMON_955       (NUM_REGULAR_OBJ_EVENT_GFX + 954)//955
#define OBJ_EVENT_GFX_POKEMON_956       (NUM_REGULAR_OBJ_EVENT_GFX + 955)//956
#define OBJ_EVENT_GFX_POKEMON_957       (NUM_REGULAR_OBJ_EVENT_GFX + 956)//957
#define OBJ_EVENT_GFX_POKEMON_958       (NUM_REGULAR_OBJ_EVENT_GFX + 957)//958
#define OBJ_EVENT_GFX_POKEMON_959       (NUM_REGULAR_OBJ_EVENT_GFX + 958)//959
#define OBJ_EVENT_GFX_POKEMON_960       (NUM_REGULAR_OBJ_EVENT_GFX + 959)//960
#define OBJ_EVENT_GFX_POKEMON_961       (NUM_REGULAR_OBJ_EVENT_GFX + 960)//961
#define OBJ_EVENT_GFX_POKEMON_962       (NUM_REGULAR_OBJ_EVENT_GFX + 961)//962
#define OBJ_EVENT_GFX_POKEMON_963       (NUM_REGULAR_OBJ_EVENT_GFX + 962)//963
#define OBJ_EVENT_GFX_POKEMON_964       (NUM_REGULAR_OBJ_EVENT_GFX + 963)//964
#define OBJ_EVENT_GFX_POKEMON_965       (NUM_REGULAR_OBJ_EVENT_GFX + 964)//965
#define OBJ_EVENT_GFX_POKEMON_966       (NUM_REGULAR_OBJ_EVENT_GFX + 965)//966
#define OBJ_EVENT_GFX_POKEMON_967       (NUM_REGULAR_OBJ_EVENT_GFX + 966)//967
#define OBJ_EVENT_GFX_POKEMON_968       (NUM_REGULAR_OBJ_EVENT_GFX + 967)//968
#define OBJ_EVENT_GFX_POKEMON_969       (NUM_REGULAR_OBJ_EVENT_GFX + 968)//969
#define OBJ_EVENT_GFX_POKEMON_970       (NUM_REGULAR_OBJ_EVENT_GFX + 969)//970
#define OBJ_EVENT_GFX_POKEMON_971       (NUM_REGULAR_OBJ_EVENT_GFX + 970)//971
#define OBJ_EVENT_GFX_POKEMON_972       (NUM_REGULAR_OBJ_EVENT_GFX + 971)//972
#define OBJ_EVENT_GFX_POKEMON_973       (NUM_REGULAR_OBJ_EVENT_GFX + 972)//973
#define OBJ_EVENT_GFX_POKEMON_974       (NUM_REGULAR_OBJ_EVENT_GFX + 973)//974
#define OBJ_EVENT_GFX_POKEMON_975       (NUM_REGULAR_OBJ_EVENT_GFX + 974)//975
#define OBJ_EVENT_GFX_POKEMON_976       (NUM_REGULAR_OBJ_EVENT_GFX + 975)//976
#define OBJ_EVENT_GFX_POKEMON_977       (NUM_REGULAR_OBJ_EVENT_GFX + 976)//977
#define OBJ_EVENT_GFX_POKEMON_978       (NUM_REGULAR_OBJ_EVENT_GFX + 977)//978
#define OBJ_EVENT_GFX_POKEMON_979       (NUM_REGULAR_OBJ_EVENT_GFX + 978)//979
#define OBJ_EVENT_GFX_POKEMON_980       (NUM_REGULAR_OBJ_EVENT_GFX + 979)//980
#define OBJ_EVENT_GFX_POKEMON_981       (NUM_REGULAR_OBJ_EVENT_GFX + 980)//981
#define OBJ_EVENT_GFX_POKEMON_982       (NUM_REGULAR_OBJ_EVENT_GFX + 981)//982
#define OBJ_EVENT_GFX_POKEMON_983       (NUM_REGULAR_OBJ_EVENT_GFX + 982)//983
#define OBJ_EVENT_GFX_POKEMON_984       (NUM_REGULAR_OBJ_EVENT_GFX + 983)//984
#define OBJ_EVENT_GFX_POKEMON_985       (NUM_REGULAR_OBJ_EVENT_GFX + 984)//985
#define OBJ_EVENT_GFX_POKEMON_986       (NUM_REGULAR_OBJ_EVENT_GFX + 985)//986
#define OBJ_EVENT_GFX_POKEMON_987       (NUM_REGULAR_OBJ_EVENT_GFX + 986)//987
#define OBJ_EVENT_GFX_POKEMON_988       (NUM_REGULAR_OBJ_EVENT_GFX + 987)//988
#define OBJ_EVENT_GFX_POKEMON_989       (NUM_REGULAR_OBJ_EVENT_GFX + 988)//989
#define OBJ_EVENT_GFX_POKEMON_990       (NUM_REGULAR_OBJ_EVENT_GFX + 989)//990
#define OBJ_EVENT_GFX_POKEMON_991       (NUM_REGULAR_OBJ_EVENT_GFX + 990)//991
#define OBJ_EVENT_GFX_POKEMON_992       (NUM_REGULAR_OBJ_EVENT_GFX + 991)//992
#define OBJ_EVENT_GFX_POKEMON_993       (NUM_REGULAR_OBJ_EVENT_GFX + 992)//993
#define OBJ_EVENT_GFX_POKEMON_994       (NUM_REGULAR_OBJ_EVENT_GFX + 993)//994
#define OBJ_EVENT_GFX_POKEMON_995       (NUM_REGULAR_OBJ_EVENT_GFX + 994)//995
#define OBJ_EVENT_GFX_POKEMON_996       (NUM_REGULAR_OBJ_EVENT_GFX + 995)//996
#define OBJ_EVENT_GFX_POKEMON_997       (NUM_REGULAR_OBJ_EVENT_GFX + 996)//997
#define OBJ_EVENT_GFX_POKEMON_998       (NUM_REGULAR_OBJ_EVENT_GFX + 997)//998
#define OBJ_EVENT_GFX_POKEMON_999       (NUM_REGULAR_OBJ_EVENT_GFX + 998)//999
#define OBJ_EVENT_GFX_POKEMON_1000      (NUM_REGULAR_OBJ_EVENT_GFX + 999)//1,000
#define OBJ_EVENT_GFX_POKEMON_1001      (NUM_REGULAR_OBJ_EVENT_GFX + 1000)//1,001
#define OBJ_EVENT_GFX_POKEMON_1002      (NUM_REGULAR_OBJ_EVENT_GFX + 1001)//1,002
#define OBJ_EVENT_GFX_POKEMON_1003      (NUM_REGULAR_OBJ_EVENT_GFX + 1002)//1,003
#define OBJ_EVENT_GFX_POKEMON_1004      (NUM_REGULAR_OBJ_EVENT_GFX + 1003)//1,004
#define OBJ_EVENT_GFX_POKEMON_1005      (NUM_REGULAR_OBJ_EVENT_GFX + 1004)//1,005
#define OBJ_EVENT_GFX_POKEMON_1006      (NUM_REGULAR_OBJ_EVENT_GFX + 1005)//1,006
#define OBJ_EVENT_GFX_POKEMON_1007      (NUM_REGULAR_OBJ_EVENT_GFX + 1006)//1,007
#define OBJ_EVENT_GFX_POKEMON_1008      (NUM_REGULAR_OBJ_EVENT_GFX + 1007)//1,008
#define OBJ_EVENT_GFX_POKEMON_1009      (NUM_REGULAR_OBJ_EVENT_GFX + 1008)//1,009
#define OBJ_EVENT_GFX_POKEMON_1010      (NUM_REGULAR_OBJ_EVENT_GFX + 1009)//1,010
#define OBJ_EVENT_GFX_POKEMON_1011      (NUM_REGULAR_OBJ_EVENT_GFX + 1010)//1,011
#define OBJ_EVENT_GFX_POKEMON_1012      (NUM_REGULAR_OBJ_EVENT_GFX + 1011)//1,012
#define OBJ_EVENT_GFX_POKEMON_1013      (NUM_REGULAR_OBJ_EVENT_GFX + 1012)//1,013
#define OBJ_EVENT_GFX_POKEMON_1014      (NUM_REGULAR_OBJ_EVENT_GFX + 1013)//1,014
#define OBJ_EVENT_GFX_POKEMON_1015      (NUM_REGULAR_OBJ_EVENT_GFX + 1014)//1,015
#define OBJ_EVENT_GFX_POKEMON_1016      (NUM_REGULAR_OBJ_EVENT_GFX + 1015)//1,016
#define OBJ_EVENT_GFX_POKEMON_1017      (NUM_REGULAR_OBJ_EVENT_GFX + 1016)//1,017

// Alternate Forms and Shit of That Nature
#define OBJ_EVENT_GFX_POKEMON_1018   	(NUM_REGULAR_OBJ_EVENT_GFX + 1017)//1,018
#define OBJ_EVENT_GFX_POKEMON_1019		(NUM_REGULAR_OBJ_EVENT_GFX + 1018)//1,019
#define OBJ_EVENT_GFX_POKEMON_1020		(NUM_REGULAR_OBJ_EVENT_GFX + 1019)//1,020
#define OBJ_EVENT_GFX_POKEMON_1021		(NUM_REGULAR_OBJ_EVENT_GFX + 1020)//1,021
#define OBJ_EVENT_GFX_POKEMON_1022		(NUM_REGULAR_OBJ_EVENT_GFX + 1021)//1,022
#define OBJ_EVENT_GFX_POKEMON_1023		(NUM_REGULAR_OBJ_EVENT_GFX + 1022)//1,023
#define OBJ_EVENT_GFX_POKEMON_1024		(NUM_REGULAR_OBJ_EVENT_GFX + 1023)//1,024
#define OBJ_EVENT_GFX_POKEMON_1025		(NUM_REGULAR_OBJ_EVENT_GFX + 1024)//1,025
#define OBJ_EVENT_GFX_POKEMON_1026		(NUM_REGULAR_OBJ_EVENT_GFX + 1025)//1,026
#define OBJ_EVENT_GFX_POKEMON_1027		(NUM_REGULAR_OBJ_EVENT_GFX + 1026)//1,027
#define OBJ_EVENT_GFX_POKEMON_1028		(NUM_REGULAR_OBJ_EVENT_GFX + 1027)//1,028
#define OBJ_EVENT_GFX_POKEMON_1029		(NUM_REGULAR_OBJ_EVENT_GFX + 1028)//1,029
#define OBJ_EVENT_GFX_POKEMON_1030		(NUM_REGULAR_OBJ_EVENT_GFX + 1029)//1,030
#define OBJ_EVENT_GFX_POKEMON_1031		(NUM_REGULAR_OBJ_EVENT_GFX + 1030)//1,031
#define OBJ_EVENT_GFX_POKEMON_1032		(NUM_REGULAR_OBJ_EVENT_GFX + 1031)//1,032
#define OBJ_EVENT_GFX_POKEMON_1033		(NUM_REGULAR_OBJ_EVENT_GFX + 1032)//1,033
#define OBJ_EVENT_GFX_POKEMON_1034		(NUM_REGULAR_OBJ_EVENT_GFX + 1033)//1,034
#define OBJ_EVENT_GFX_POKEMON_1035		(NUM_REGULAR_OBJ_EVENT_GFX + 1034)//1,035
#define OBJ_EVENT_GFX_POKEMON_1036		(NUM_REGULAR_OBJ_EVENT_GFX + 1035)//1,036
#define OBJ_EVENT_GFX_POKEMON_1037		(NUM_REGULAR_OBJ_EVENT_GFX + 1036)//1,037
#define OBJ_EVENT_GFX_POKEMON_1038		(NUM_REGULAR_OBJ_EVENT_GFX + 1037)//1,038
#define OBJ_EVENT_GFX_POKEMON_1039		(NUM_REGULAR_OBJ_EVENT_GFX + 1038)//1,039
#define OBJ_EVENT_GFX_POKEMON_1040		(NUM_REGULAR_OBJ_EVENT_GFX + 1039)//1,040
#define OBJ_EVENT_GFX_POKEMON_1041		(NUM_REGULAR_OBJ_EVENT_GFX + 1040)//1,041
#define OBJ_EVENT_GFX_POKEMON_1042		(NUM_REGULAR_OBJ_EVENT_GFX + 1041)//1,042
#define OBJ_EVENT_GFX_POKEMON_1043		(NUM_REGULAR_OBJ_EVENT_GFX + 1042)//1,043
#define OBJ_EVENT_GFX_POKEMON_1044		(NUM_REGULAR_OBJ_EVENT_GFX + 1043)//1,044
#define OBJ_EVENT_GFX_POKEMON_1045		(NUM_REGULAR_OBJ_EVENT_GFX + 1044)//1,045
#define OBJ_EVENT_GFX_POKEMON_1046		(NUM_REGULAR_OBJ_EVENT_GFX + 1045)//1,046
#define OBJ_EVENT_GFX_POKEMON_1047		(NUM_REGULAR_OBJ_EVENT_GFX + 1046)//1,047
#define OBJ_EVENT_GFX_POKEMON_1048		(NUM_REGULAR_OBJ_EVENT_GFX + 1047)//1,048
#define OBJ_EVENT_GFX_POKEMON_1049		(NUM_REGULAR_OBJ_EVENT_GFX + 1048)//1,049
#define OBJ_EVENT_GFX_POKEMON_1050		(NUM_REGULAR_OBJ_EVENT_GFX + 1049)//1,050
#define OBJ_EVENT_GFX_POKEMON_1051		(NUM_REGULAR_OBJ_EVENT_GFX + 1050)//1,051
#define OBJ_EVENT_GFX_POKEMON_1052		(NUM_REGULAR_OBJ_EVENT_GFX + 1051)//1,052
#define OBJ_EVENT_GFX_POKEMON_1053		(NUM_REGULAR_OBJ_EVENT_GFX + 1052)//1,053
#define OBJ_EVENT_GFX_POKEMON_1054		(NUM_REGULAR_OBJ_EVENT_GFX + 1053)//1,054

#define NUM_OBJ_EVENT_GFX               (OBJ_EVENT_GFX_POKEMON_1054 + 1)

#define species_gfx(species) ((species + (NUM_REGULAR_OBJ_EVENT_GFX - 1)))


// NOTE: By default, the max value for NUM_OBJ_EVENT_GFX is 242.
//
// Object event graphics ids are 1 byte in size (max value of 255), and the dynamic
// graphics ids that start after NUM_OBJ_EVENT_GFX reach this limit. No graphics id
// uses the value 239 itself, so removing the "+ 1" in OBJ_EVENT_GFX_VARS would
// allow increasing NUM_OBJ_EVENT_GFX to 240. There are also a handful of unused
// object graphics that can be removed. If more graphics are needed, anything that
// stores graphics ids will need to be increased in size. See wiki entry below:
// https://github.com/pret/pokeemerald/wiki/Feature-Branches#overworld-expansion


// These are dynamic object gfx ids.
// They correspond with the values of the VAR_OBJ_GFX_ID_X vars.
// More info about them in include/constants/vars.h
#define OBJ_EVENT_GFX_VARS   (NUM_OBJ_EVENT_GFX + 1)
#define OBJ_EVENT_GFX_VAR_0  (OBJ_EVENT_GFX_VARS + 0x0) // 240
#define OBJ_EVENT_GFX_VAR_1  (OBJ_EVENT_GFX_VARS + 0x1)
#define OBJ_EVENT_GFX_VAR_2  (OBJ_EVENT_GFX_VARS + 0x2)
#define OBJ_EVENT_GFX_VAR_3  (OBJ_EVENT_GFX_VARS + 0x3)
#define OBJ_EVENT_GFX_VAR_4  (OBJ_EVENT_GFX_VARS + 0x4)
#define OBJ_EVENT_GFX_VAR_5  (OBJ_EVENT_GFX_VARS + 0x5)
#define OBJ_EVENT_GFX_VAR_6  (OBJ_EVENT_GFX_VARS + 0x6)
#define OBJ_EVENT_GFX_VAR_7  (OBJ_EVENT_GFX_VARS + 0x7)
#define OBJ_EVENT_GFX_VAR_8  (OBJ_EVENT_GFX_VARS + 0x8)
#define OBJ_EVENT_GFX_VAR_9  (OBJ_EVENT_GFX_VARS + 0x9)
#define OBJ_EVENT_GFX_VAR_A  (OBJ_EVENT_GFX_VARS + 0xA)
#define OBJ_EVENT_GFX_VAR_B  (OBJ_EVENT_GFX_VARS + 0xB)
#define OBJ_EVENT_GFX_VAR_C  (OBJ_EVENT_GFX_VARS + 0xC)
#define OBJ_EVENT_GFX_VAR_D  (OBJ_EVENT_GFX_VARS + 0xD)
#define OBJ_EVENT_GFX_VAR_E  (OBJ_EVENT_GFX_VARS + 0xE)
#define OBJ_EVENT_GFX_VAR_F  (OBJ_EVENT_GFX_VARS + 0xF) // 255

#define SHADOW_SIZE_S   0
#define SHADOW_SIZE_M   1
#define SHADOW_SIZE_L   2
#define SHADOW_SIZE_XL  3

#define F_INANIMATE                        (1 << 6)
#define F_DISABLE_REFLECTION_PALETTE_LOAD  (1 << 7)

#define TRACKS_NONE       0
#define TRACKS_FOOT       1
#define TRACKS_BIKE_TIRE  2

#define FIRST_DECORATION_SPRITE_GFX OBJ_EVENT_GFX_PICHU_DOLL

#define OBJ_KIND_NORMAL 0
#define OBJ_KIND_CLONE  255 // Exclusive to FRLG

// Special object event local ids
#define OBJ_EVENT_ID_PLAYER 0xFF
#define OBJ_EVENT_ID_CAMERA 0x7F

// Object event local ids referenced in C files
#define LOCALID_ROUTE111_PLAYER_FALLING 45
#define LOCALID_BIRTH_ISLAND_EXTERIOR_ROCK 1
#define LOCALID_FARAWAY_ISLAND_MEW 1
#define LOCALID_UNION_ROOM_PLAYER_4 2
#define LOCALID_UNION_ROOM_PLAYER_8 3
#define LOCALID_UNION_ROOM_PLAYER_7 4
#define LOCALID_UNION_ROOM_PLAYER_6 5
#define LOCALID_UNION_ROOM_PLAYER_5 6
#define LOCALID_UNION_ROOM_PLAYER_3 7
#define LOCALID_UNION_ROOM_PLAYER_2 8
#define LOCALID_UNION_ROOM_PLAYER_1 9
#define LOCALID_BATTLE_TOWER_LOBBY_REPORTER 5
#define LOCALID_TRUCK_BOX_TOP 1
#define LOCALID_TRUCK_BOX_BOTTOM_L 2
#define LOCALID_TRUCK_BOX_BOTTOM_R 3
#define LOCALID_OLDALE_MART_CLERK 1
#define LOCALID_LAVARIDGE_MART_CLERK 1
#define LOCALID_FALLARBOR_MART_CLERK 1
#define LOCALID_VERDANTURF_MART_CLERK 1
#define LOCALID_PETALBURG_MART_CLERK 1
#define LOCALID_SLATEPORT_MART_CLERK 1
#define LOCALID_MAUVILLE_MART_CLERK 1
#define LOCALID_RUSTBORO_MART_CLERK 1
#define LOCALID_FORTREE_MART_CLERK 1
#define LOCALID_MOSSDEEP_MART_CLERK 1
#define LOCALID_SOOTOPOLIS_MART_CLERK 1
#define LOCALID_BATTLE_FRONTIER_MART_CLERK 1
#define LOCALID_SLATEPORT_ENERGY_GURU 25

#endif  // GUARD_CONSTANTS_EVENT_OBJECTS_H
